declare -x AISC_ACCOUNT_NAME="msrresrchvc"
declare -x AISC_ARM_CORRELATION_ID=""
declare -x AISC_CAPACITY_COUNT="4"
declare -x AISC_CAPACITY_ID="NC_A100_v4_NvidiaGpu-Units"
declare -x AISC_CLIENT_REQUEST_ID=""
declare -x AISC_COMMAND_EXECUTION_USER="aiscuser"
declare -x AISC_CONTAINER_CAPABILITIES="SYS_ADMIN,DAC_READ_SEARCH,SYS_PTRACE"
declare -x AISC_CONTAINER_GPU="4"
declare -x AISC_CONTAINER_SECURITY_OPTIONS="apparmor=singularityarmor.armor"
declare -x AISC_ENABLE_FUSE_DEVICE="true"
declare -x AISC_ENABLE_LUSTRE_FILESYSTEM="false"
declare -x AISC_ENABLE_WEKA_FILESYSTEM="false"
declare -x AISC_HEALTH_EVENT_CORRELATION_ID="e90342e8-2730-4cda-bc94-054889e466f3\$2dcef2e0-136e-4db5-a481-e79a93b7cce6"
declare -x AISC_HOST_FAMILY="NvidiaGpu"
declare -x AISC_INFINIBAND_ENABLED="false"
declare -x AISC_INSTANCE_TYPE="Singularity.NC96ad_A100_v4"
declare -x AISC_JOB_EXECUTION_MODE="basic"
declare -x AISC_JOB_INSTANCE_ID="2dcef2e0-136e-4db5-a481-e79a93b7cce6"
declare -x AISC_JOB_NAME="helpful_shampoo_mj0cvl4kcg"
declare -x AISC_JOB_RESOURCE_ID="/subscriptions/ba709ca5-1a2c-479c-a1cb-6e0346b81bf1/resourcegroups/singularityhobo/providers/Microsoft.Singularity/accounts/msrresrchvc/jobs/helpful_shampoo_mj0cvl4kcg"
declare -x AISC_LUSTRE_HOST_PATH="/mntdlws/lustre/{0}"
declare -x AISC_NODE_INSTANCE_ID="2dcef2e0-136e-4db5-a481-e79a93b7cce6"
declare -x AISC_NODE_RESOURCE_ID="/subscriptions/ba709ca5-1a2c-479c-a1cb-6e0346b81bf1/resourcegroups/singularityhobo/providers/Microsoft.Singularity/accounts/msrresrchvc/jobs/helpful_shampoo_mj0cvl4kcg"
declare -x AISC_PRIVILEGED="false"
declare -x AISC_RESOURCE_GROUP_NAME="singularityhobo"
declare -x AISC_RESOURCE_ID="/subscriptions/ba709ca5-1a2c-479c-a1cb-6e0346b81bf1/resourcegroups/singularityhobo/providers/Microsoft.Singularity/accounts/msrresrchvc/jobs/helpful_shampoo_mj0cvl4kcg"
declare -x AISC_RESOURCE_INSTANCE_ID="2dcef2e0-136e-4db5-a481-e79a93b7cce6"
declare -x AISC_SCRATCH_DIR="/scratch"
declare -x AISC_SCRATCH_STORAGE_ENABLE="true"
declare -x AISC_SCRATCH_STORAGE_SIZE_GB="3072"
declare -x AISC_SERVICE_PACKAGE_GPU="4"
declare -x AISC_SERVICE_PACKAGE_INFINIBAND_ENABLED="false"
declare -x AISC_SERVICE_PACKAGE_SCRATCH_STORAGE_ENABLE="true"
declare -x AISC_SUBSCRIPTION_ID="ba709ca5-1a2c-479c-a1cb-6e0346b81bf1"
declare -x AISC_WEKA_HOST_PATH="/mntdlws/weka/{0}"
declare -x AKS_ENABLE_HEALTH_PRECHECK="true"
declare -x AKS_HELM_CHART_VERSION="1.1.0335513366"
declare -x AKS_INSTANCE_TYPE="NC_A100_v4_NvidiaGpu-Units"
declare -x AMLCHM_ENABLE_HEALTH_PRECHECK="true"
declare -x AMLT_CODE="/tmp/amlt-code-download"
declare -x AMLT_DEFAULT="/mnt/default/"
declare -x AMLT_EXPERIMENT_NAME="polite-anchovy"
declare -x AMLT_JOB_ID="7226550736.03454-e95bcd5a-1159"
declare -x AMLT_JOB_NAME="yif-unirun-4x80Ga100"
declare -x AMLT_LOGS_DIR="/output/"
declare -x AMLT_OUTPUT_DIR="/output/"
declare -x AMLT_RESULTS="/scratch/azureml/cr/j/b5e4aee59bb6481db8ad5d94681dd957/cap/data-capability/wd/amlt_results"
declare -x AMLT_SERVICE="sing"
declare -x APPLICATION_VERSION="1.1.03355.13366"
declare -x AZCOPY_AUTO_LOGIN_TYPE="MSI"
declare -x AZUREML_ARM_PROJECT_NAME="vllm-sh-gcr12301-abd9158f"
declare -x AZUREML_ARM_RESOURCEGROUP="msra-sh-aml-rg"
declare -x AZUREML_ARM_SUBSCRIPTION="c4c534bc-9978-4974-9c87-551f7c5754ef"
declare -x AZUREML_ARM_WORKSPACE_NAME="msra-sh-aml-ws"
declare -x AZUREML_COMMON_RUNTIME_USE_RH_RUN_ATTEMPT_CONTROL_LOGIC="true"
declare -x AZUREML_COMPUTE_NAME="aisupercomputer"
declare -x AZUREML_COMPUTE_RESERVED_DISK_SPACE="494780232499"
declare -x AZUREML_COMPUTE_TYPE="Singularity"
declare -x AZUREML_CONDA_ENVIRONMENT_PATH="/opt/conda/envs/ptca"
declare -x AZUREML_CR_AZUREML_CONTEXT="{\"subscription_id\":\"c4c534bc-9978-4974-9c87-551f7c5754ef\",\"resource_group\":\"msra-sh-aml-rg\",\"workspace_name\":\"msra-sh-aml-ws\",\"workspace_id\":\"dc1bc560-c630-4be6-bdf3-67e1367437d9\",\"service_endpoint\":\"https://westus2.api.azureml.ms\",\"service_cert_endpoint\":\"https://westus2.cert.api.azureml.ms\",\"discovery_endpoint\":\"https://westus2.api.azureml.ms/discovery\",\"experiment_name\":\"vllm-sh-gcr12301-abd9158f\",\"experiment_id\":\"8ddba47b-5442-4000-8bd2-be558857ecce\",\"root_run_id\":\"helpful_shampoo_mj0cvl4kcg\",\"run_id\":\"helpful_shampoo_mj0cvl4kcg\",\"run_token\":\"eyJhbGciOiJSUzI1NiIsImtpZCI6IjhDMTAzQTRDMEI3QTAxQzQyOTE3QTlBMzVCRjJEMkE2NEQyMTI2NDAiLCJ0eXAiOiJKV1QifQ.eyJyb2xlIjoiQ29udHJpYnV0b3IiLCJzY29wZSI6Ii9zdWJzY3JpcHRpb25zL2M0YzUzNGJjLTk5NzgtNDk3NC05Yzg3LTU1MWY3YzU3NTRlZi9yZXNvdXJjZUdyb3Vwcy9tc3JhLXNoLWFtbC1yZy9wcm92aWRlcnMvTWljcm9zb2Z0Lk1hY2hpbmVMZWFybmluZ1NlcnZpY2VzL3dvcmtzcGFjZXMvbXNyYS1zaC1hbWwtd3MiLCJhY2NvdW50aWQiOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDAiLCJ3b3Jrc3BhY2VJZCI6ImRjMWJjNTYwLWM2MzAtNGJlNi1iZGYzLTY3ZTEzNjc0MzdkOSIsInByb2plY3RpZCI6IjAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDAwMCIsImRpc2NvdmVyeSI6InVyaTovL2Rpc2NvdmVyeXVyaS8iLCJ0aWQiOiI3MmY5ODhiZi04NmYxLTQxYWYtOTFhYi0yZDdjZDAxMWRiNDciLCJvaWQiOiI4YTU4OTcyNS03NjIyLTQxZGEtODE4Mi04ZGE4MTEyN2RkNzIiLCJwdWlkIjoiMTAwMzIwMDM4RDM0MEUzMyIsImlzcyI6ImF6dXJlbWwiLCJhcHBpZCI6IllpZmFuIFlhbmcgKFNDLUFMVCkiLCJleHAiOjE3NzUyNDU2NzMsImF1ZCI6ImF6dXJlbWwifQ.qUNWzCsOQRImJaPHTy0Eca0xKbpLQgBsEMpcww7A7VKx_8u848jo6sWbSlWOBCRsvwpe56LkSVtHiqrKsV_tllYNi5vc9WJAdpA6m6t9Arp-Eym8ZLvgeZKspoALHsYHKad31quNgC_AGLebrMnisQoWa98aLpvYyjHm2P8evuH9W2Gz__uLammX4C0OHuUI8sN1941NGtFyUhw9OnIemN3u_FipLKbk8yMAwmNPsDnlEpBtMuPEY0_GlmCrlryagWZsUkK6s5ntTfs8aZ4ZKfKPyRz4XHFYkWKbKBopNMfUdf9FsYDlaN66mDnBJv63ClYot5QjoGYsX-qH09suPw\",\"run_history_service_endpoint\":\"https://westus2.api.azureml.ms\",\"data_container_id\":\"dcid.helpful_shampoo_mj0cvl4kcg\",\"run_uuid\":\"b5e4aee5-9bb6-481d-b8ad-5d94681dd957\",\"compute_type\":\"Singularity\"}"
declare -x AZUREML_CR_COMPUTE_CONTEXT="{\"cluster_name\":\"aisupercomputer\",\"node_id\":{\"Literal\":\"node-0\"},\"vm_id\":null,\"run_attempt_count\":1,\"gpu_count\":null,\"vm_size\":null,\"readable_cluster_name\":null,\"vm_priority\":null,\"use_vnet_or_private_link\":false}"
declare -x AZUREML_CR_COMPUTE_TYPE="singularity"
declare -x AZUREML_CR_CORRELATION_ID="helpful_shampoo_mj0cvl4kcg"
declare -x AZUREML_CR_CS_CAPABILITY_ADDRESS="/scratch/azureml/cr/j/b5e4aee59bb6481db8ad5d94681dd957/.grpc/cs-capability:0"
declare -x AZUREML_CR_CS_CAPABILITY_HOST="127.0.0.1"
declare -x AZUREML_CR_CS_CAPABILITY_PATH="/scratch/azureml/cr/j/b5e4aee59bb6481db8ad5d94681dd957/cap/cs-capability/wd"
declare -x AZUREML_CR_CS_CAPABILITY_RUNNING="TRUE"
declare -x AZUREML_CR_CURRENT_RUN_ATTEMPT="1"
declare -x AZUREML_CR_DATA_CAPABILITY_ADDRESS="/scratch/azureml/cr/j/b5e4aee59bb6481db8ad5d94681dd957/.grpc/data-capability:0"
declare -x AZUREML_CR_DATA_CAPABILITY_HOST="127.0.0.1"
declare -x AZUREML_CR_DATA_CAPABILITY_PATH="/scratch/azureml/cr/j/b5e4aee59bb6481db8ad5d94681dd957/cap/data-capability/wd"
declare -x AZUREML_CR_DATA_CAPABILITY_RUNNING="TRUE"
declare -x AZUREML_CR_ENABLE_RUN_ATTEMPT_COUNT_BY_RUN_HISTORY="true"
declare -x AZUREML_CR_EXECUTION_WORKING_DIR_PATH="/scratch/azureml/cr/j/b5e4aee59bb6481db8ad5d94681dd957/exe/wd"
declare -x AZUREML_CR_EXECUTION_WRAPPER_PATH="/scratch/azureml/cr/j/b5e4aee59bb6481db8ad5d94681dd957/cap/lifecycler/wd"
declare -x AZUREML_CR_EXECUTOR_ADDRESS="/scratch/azureml/cr/j/b5e4aee59bb6481db8ad5d94681dd957/.grpc/executor:0"
declare -x AZUREML_CR_EXECUTOR_CONFIG="eyJleGVjdXRpb25fd29ya2luZ19kaXIiOiIvc2NyYXRjaC9henVyZW1sL2NyL2ovYjVlNGFlZTU5YmI2NDgxZGI4YWQ1ZDk0NjgxZGQ5NTcvZXhlL3dkIiwiZXhlY3V0b3JfYWRkcmVzcyI6Ii9zY3JhdGNoL2F6dXJlbWwvY3Ivai9iNWU0YWVlNTliYjY0ODFkYjhhZDVkOTQ2ODFkZDk1Ny8uZ3JwYy9leGVjdXRvcjowIiwibGlmZWN5Y2xlcl9hZGRyZXNzIjoiL3NjcmF0Y2gvYXp1cmVtbC9jci9qL2I1ZTRhZWU1OWJiNjQ4MWRiOGFkNWQ5NDY4MWRkOTU3Ly5ncnBjL2xpZmVjeWNsZXI6MCIsImRpc3RyaWJ1dGVkX2NvbmZpZyI6bnVsbCwidXNlX21waV9yc2hfYWdlbnQiOm51bGwsImV4ZWN1dG9yX2NvbmZpZyI6eyJlbmFibGVfc3RkX2xvZ19zdHJlYW1pbmciOnRydWUsImVuYWJsZV90ZXJtaW5hdGlvbl9zaWduYWxfaGFuZGxpbmciOnRydWUsImVycm9yX3BhdHRlcm5fanNvbl9maWxlX21pZF9leGVjdXRpb24iOiIvb3B0L21pY3Jvc29mdC9zaW5ndWxhcml0eS91c2VyL2NvbW1vbi9zZXJ2aWNlcy91c2VyX25vZGVfYWdlbnQvYXBwL0ZhaWx1cmVQYXR0ZXJucy5qc29uIiwiZXJyb3JfcGF0dGVybl9qc29uX2ZpbGVzX3Bvc3RfZXhlY3V0aW9uIjpbIi9vcHQvbWljcm9zb2Z0L3Npbmd1bGFyaXR5L3VzZXIvY29tbW9uL3NlcnZpY2VzL3VzZXJfbm9kZV9hZ2VudC9hcHAvRmFpbHVyZVBhdHRlcm5zLmpzb24iXSwiZXhlX3dyYXBwZXJfZGVzdCI6Ii9zY3JhdGNoL2F6dXJlbWwvY3IiLCJza2lwX3VzZXJfbG9nX2ZpbGVfZ2VuZXJhdGlvbiI6ZmFsc2V9fQ"
declare -x AZUREML_CR_GRPC_ADDRESS_BASE="/scratch/azureml/cr/j/b5e4aee59bb6481db8ad5d94681dd957/.grpc"
declare -x AZUREML_CR_GRPC_ADDRESS_SPEC="{\"Uds\":{\"base_address\":\"/scratch/azureml/cr/j/b5e4aee59bb6481db8ad5d94681dd957/.grpc\"}}"
declare -x AZUREML_CR_HOSTTOOLS_CAPABILITY_ADDRESS="/scratch/azureml/cr/j/b5e4aee59bb6481db8ad5d94681dd957/.grpc/hosttools-capability:0"
declare -x AZUREML_CR_HOSTTOOLS_CAPABILITY_HOST="127.0.0.1"
declare -x AZUREML_CR_HOSTTOOLS_CAPABILITY_PATH="/scratch/azureml/cr/j/b5e4aee59bb6481db8ad5d94681dd957/cap/hosttools-capability/wd"
declare -x AZUREML_CR_HOSTTOOLS_CAPABILITY_RUNNING="TRUE"
declare -x AZUREML_CR_HT_CAP_azureml_logs_PATH="/scratch/azureml/cr/j/b5e4aee59bb6481db8ad5d94681dd957/exe/wd/azureml-logs"
declare -x AZUREML_CR_HT_CAP_logs_PATH="/scratch/azureml/cr/j/b5e4aee59bb6481db8ad5d94681dd957/exe/wd/logs"
declare -x AZUREML_CR_HT_CAP_outputs_PATH="/scratch/azureml/cr/j/b5e4aee59bb6481db8ad5d94681dd957/exe/wd/outputs"
declare -x AZUREML_CR_HT_CAP_user_logs_PATH="/scratch/azureml/cr/j/b5e4aee59bb6481db8ad5d94681dd957/exe/wd/user_logs"
declare -x AZUREML_CR_INTERACTIVE_CAPABILITY_ADDRESS="/scratch/azureml/cr/j/b5e4aee59bb6481db8ad5d94681dd957/.grpc/interactive-capability:0"
declare -x AZUREML_CR_INTERACTIVE_CAPABILITY_HOST="127.0.0.1"
declare -x AZUREML_CR_INTERACTIVE_CAPABILITY_PATH="/scratch/azureml/cr/j/b5e4aee59bb6481db8ad5d94681dd957/cap/interactive-capability/wd"
declare -x AZUREML_CR_INTERACTIVE_CAPABILITY_RUNNING="TRUE"
declare -x AZUREML_CR_IS_PARALLEL_MODE_ENABLED="false"
declare -x AZUREML_CR_JOB_LOCATION="westus2"
declare -x AZUREML_CR_LEASE_ACQUIRED="false"
declare -x AZUREML_CR_LIFECYCLER_PATH="/scratch/azureml/cr/j/b5e4aee59bb6481db8ad5d94681dd957/cap/lifecycler/wd"
declare -x AZUREML_CR_NODE_RANK="0"
declare -x AZUREML_CR_RUN_ATTEMPT_CONTROL_LOGIC="RunHistoryMetadata"
declare -x AZUREML_CR_RUN_ATTEMPT_CREATED_BY_ES="true"
declare -x AZUREML_CR_SNAPSHOT_CAPABILITY_ADDRESS="/scratch/azureml/cr/j/b5e4aee59bb6481db8ad5d94681dd957/.grpc/snapshot-capability:0"
declare -x AZUREML_CR_SNAPSHOT_CAPABILITY_HOST="127.0.0.1"
declare -x AZUREML_CR_SNAPSHOT_CAPABILITY_PATH="/scratch/azureml/cr/j/b5e4aee59bb6481db8ad5d94681dd957/cap/snapshot-capability/wd"
declare -x AZUREML_CR_SNAPSHOT_CAPABILITY_RUNNING="TRUE"
declare -x AZUREML_CR_TELEMETRY_CONFIG="{\"collector\":{\"receiver\":null,\"exporter\":{\"appinsights\":{\"instrumentation_key\":\"b1d06868-1df3-4563-b998-8ade07ff7165\",\"endpoint_suffix\":\"services.visualstudio.com\",\"ingestion_endpoint\":null,\"aad_audience\":null},\"jaeger\":null,\"prometheus\":null,\"timeout_millis\":null,\"level\":null}},\"logger\":{\"console\":{\"sink\":\"stdout\",\"level\":\"info\",\"enabled\":true,\"ansi\":false},\"appinsights\":{\"instrumentation_key\":\"b1d06868-1df3-4563-b998-8ade07ff7165\",\"level\":\"info\",\"enabled\":true,\"endpoint_suffix\":\"services.visualstudio.com\",\"ingestion_endpoint\":null,\"aad_audience\":null},\"file\":{\"extension\":\"log\",\"level\":\"info\",\"enabled\":true}},\"node_rank\":null,\"node_id\":\"node-0\",\"disable_sensitive_scrub\":null,\"attempt_id\":\"1\"}"
declare -x AZUREML_DATAREFERENCE_AMLT_CODE="/tmp/amlt-code-download"
declare -x AZUREML_DATAREFERENCE_AZURE_ML_INPUT_AMLT_CODE="/tmp/amlt-code-download"
declare -x AZUREML_DATAREFERENCE_AZURE_ML_INPUT_amlt_code="/tmp/amlt-code-download"
declare -x AZUREML_DATAREFERENCE_amlt_code="/tmp/amlt-code-download"
declare -x AZUREML_DATAREFERENCE_amlt_default="/mnt/default"
declare -x AZUREML_DATAREFERENCE_data="/datasets"
declare -x AZUREML_DATAREFERENCE_input="/blob"
declare -x AZUREML_DATAREFERENCE_output="/output"
declare -x AZUREML_DATAREFERENCE_zehui="/zehui"
declare -x AZUREML_DATASET_ENVIRONMENT_VARS="amlt_code:download"
declare -x AZUREML_DATASET_FILE_OUTPUTS="data;zehui;output;input;amlt_default;amlt_results"
declare -x AZUREML_DISCOVERY_SERVICE_ENDPOINT="https://westus2.api.azureml.ms/discovery"
declare -x AZUREML_EXPERIMENT_ID="8ddba47b-5442-4000-8bd2-be558857ecce"
declare -x AZUREML_EXPERIMENT_SCOPE="/subscriptions/c4c534bc-9978-4974-9c87-551f7c5754ef/resourceGroups/msra-sh-aml-rg/providers/Microsoft.MachineLearningServices/workspaces/msra-sh-aml-ws/experiments/vllm-sh-gcr12301-abd9158f"
declare -x AZUREML_NODE_COUNT="1"
declare -x AZUREML_PROCESS_NAME="main"
declare -x AZUREML_PYTHON_INTERPRETER_PATH="python"
declare -x AZUREML_ROOT_RUN_ID="helpful_shampoo_mj0cvl4kcg"
declare -x AZUREML_RUNTIME_JOB_SPEC_FILE_PATH="/scratch/workspaceblobstore/azureml/helpful_shampoo_mj0cvl4kcg/.jobspec"
declare -x AZUREML_RUNTIME_JOB_SPEC_HASH="bc53c702cf3895d087327464a4e09fe59fecb2e2eb78d57df156acb76f896c4c"
declare -x AZUREML_RUNTIME_JOB_SPEC_SAS_URL="https://msrashamlws4466460092.blob.core.windows.net/azureml-blobstore-dc1bc560-c630-4be6-bdf3-67e1367437d9/azureml/helpful_shampoo_mj0cvl4kcg/.jobspec?sv=2019-07-07&sr=c&sig=htY9IkoDKoPbklwcKeVF3iK9aSipPhxyz3at%2BOzEW9s%3D&skoid=780cb0c4-18a1-4be3-922b-a66f484d1557&sktid=72f988bf-86f1-41af-91ab-2d7cd011db47&skt=2026-03-13T17%3A05%3A49Z&ske=2026-03-20T17%3A05%3A49Z&sks=b&skv=2019-07-07&st=2026-03-13T17%3A37%3A57Z&se=2026-03-20T16%3A55%3A49Z&sp=r"
declare -x AZUREML_RUN_CONFIGURATION="azureml-setup/mutated_run_configuration.json"
declare -x AZUREML_RUN_HISTORY_SERVICE_ENDPOINT="https://westus2.api.azureml.ms"
declare -x AZUREML_RUN_ID="helpful_shampoo_mj0cvl4kcg"
declare -x AZUREML_RUN_IV="hB1HvrzcRL6Y6mMAialiEg=="
declare -x AZUREML_RUN_TOKEN="eyJhbGciOiJSUzI1NiIsImtpZCI6IjhDMTAzQTRDMEI3QTAxQzQyOTE3QTlBMzVCRjJEMkE2NEQyMTI2NDAiLCJ0eXAiOiJKV1QifQ.eyJyb2xlIjoiQ29udHJpYnV0b3IiLCJzY29wZSI6Ii9zdWJzY3JpcHRpb25zL2M0YzUzNGJjLTk5NzgtNDk3NC05Yzg3LTU1MWY3YzU3NTRlZi9yZXNvdXJjZUdyb3Vwcy9tc3JhLXNoLWFtbC1yZy9wcm92aWRlcnMvTWljcm9zb2Z0Lk1hY2hpbmVMZWFybmluZ1NlcnZpY2VzL3dvcmtzcGFjZXMvbXNyYS1zaC1hbWwtd3MiLCJhY2NvdW50aWQiOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDAiLCJ3b3Jrc3BhY2VJZCI6ImRjMWJjNTYwLWM2MzAtNGJlNi1iZGYzLTY3ZTEzNjc0MzdkOSIsInByb2plY3RpZCI6IjAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDAwMCIsImRpc2NvdmVyeSI6InVyaTovL2Rpc2NvdmVyeXVyaS8iLCJ0aWQiOiI3MmY5ODhiZi04NmYxLTQxYWYtOTFhYi0yZDdjZDAxMWRiNDciLCJvaWQiOiI4YTU4OTcyNS03NjIyLTQxZGEtODE4Mi04ZGE4MTEyN2RkNzIiLCJwdWlkIjoiMTAwMzIwMDM4RDM0MEUzMyIsImlzcyI6ImF6dXJlbWwiLCJhcHBpZCI6IllpZmFuIFlhbmcgKFNDLUFMVCkiLCJleHAiOjE3NzUyNDU2NzMsImF1ZCI6ImF6dXJlbWwifQ.qUNWzCsOQRImJaPHTy0Eca0xKbpLQgBsEMpcww7A7VKx_8u848jo6sWbSlWOBCRsvwpe56LkSVtHiqrKsV_tllYNi5vc9WJAdpA6m6t9Arp-Eym8ZLvgeZKspoALHsYHKad31quNgC_AGLebrMnisQoWa98aLpvYyjHm2P8evuH9W2Gz__uLammX4C0OHuUI8sN1941NGtFyUhw9OnIemN3u_FipLKbk8yMAwmNPsDnlEpBtMuPEY0_GlmCrlryagWZsUkK6s5ntTfs8aZ4ZKfKPyRz4XHFYkWKbKBopNMfUdf9FsYDlaN66mDnBJv63ClYot5QjoGYsX-qH09suPw"
declare -x AZUREML_RUN_TOKEN_EXPIRY="1775245673"
declare -x AZUREML_RUN_TOKEN_PASS="50e1327a-2588-4c05-bef7-59bb12f11326"
declare -x AZUREML_RUN_TOKEN_RAND="b2d85e0a-e245-4f0a-b734-78bb47e8a783"
declare -x AZUREML_RUN_UNIQUE_SYMMETRIC_KEY="XvJSXt7+B1KmFxSdpnROEpDKG9fXjWer8gRPYjDE5XM="
declare -x AZUREML_SERVICE_CERT_ENDPOINT="https://westus2.cert.api.azureml.ms"
declare -x AZUREML_SERVICE_ENDPOINT="https://westus2.api.azureml.ms"
declare -x AZUREML_USER_OID="8a589725-7622-41da-8182-8da81127dd72"
declare -x AZUREML_WORKSPACE_ID="dc1bc560-c630-4be6-bdf3-67e1367437d9"
declare -x AZUREML_WORKSPACE_SCOPE="/subscriptions/c4c534bc-9978-4974-9c87-551f7c5754ef/resourceGroups/msra-sh-aml-rg/providers/Microsoft.MachineLearningServices/workspaces/msra-sh-aml-ws"
declare -x AZURE_CLIENT_ID="4862a06d-c6c5-4be5-80c9-9875ec3d93b3"
declare -x AZURE_ML_INPUT_AMLT_CODE="/tmp/amlt-code-download"
declare -x AZURE_ML_INPUT_amlt_code="/tmp/amlt-code-download"
declare -x AZURE_ML_OUTPUT_AMLT_DEFAULT="/mnt/default/"
declare -x AZURE_ML_OUTPUT_AMLT_RESULTS="/scratch/azureml/cr/j/b5e4aee59bb6481db8ad5d94681dd957/cap/data-capability/wd/amlt_results"
declare -x AZURE_ML_OUTPUT_DATA="/datasets/"
declare -x AZURE_ML_OUTPUT_INPUT="/blob/"
declare -x AZURE_ML_OUTPUT_OUTPUT="/output/"
declare -x AZURE_ML_OUTPUT_ZEHUI="/zehui/"
declare -x AZURE_ML_OUTPUT_amlt_default="/mnt/default/"
declare -x AZURE_ML_OUTPUT_amlt_results="/scratch/azureml/cr/j/b5e4aee59bb6481db8ad5d94681dd957/cap/data-capability/wd/amlt_results"
declare -x AZURE_ML_OUTPUT_data="/datasets/"
declare -x AZURE_ML_OUTPUT_input="/blob/"
declare -x AZURE_ML_OUTPUT_output="/output/"
declare -x AZURE_ML_OUTPUT_zehui="/zehui/"
declare -x AZ_BATCHAI_JOB_MASTER_NODE_IP="localhost"
declare -x AZ_BATCHAI_JOB_WORK_DIR="/scratch/azureml/cr/j/b5e4aee59bb6481db8ad5d94681dd957/exe/wd"
declare -x AZ_BATCHAI_MPI_MASTER_NODE="localhost"
declare -x AZ_BATCHAI_NODE_IP="node-0"
declare -x AZ_BATCH_JOB_ID="helpful_shampoo_mj0cvl4kcg"
declare -x AZ_BATCH_MASTER_NODE="node-0:9500"
declare -x AZ_BATCH_NODE_ID="node-0"
declare -x AZ_SINGULARITY_STDOUTERR_PATH="/scratch/workspaceblobstore/azureml/helpful_shampoo_mj0cvl4kcg/azureml_compute_logs"
declare -x BACKEND="gloo"
declare -x BLOB_MOUNT_OPTIONS=""
declare -x CACHE_SERVER_LIST=""
declare -x CACHE_SERVER_PORT=""
declare -x CACHE_SERVER_PORT_LOCAL="9067"
declare -x CHECKPOINT_PARTITION_COUNT="MustSpecifyViaApplicationParameters"
declare -x CHECKPOINT_STAGING_PATH_PREFIX="/mnt/resource/singularity/criu/staging/worker"
declare -x CHECKPOINT_STORAGE_CONNECTION_STRING_0="_plaintext_"
declare -x CHECKPOINT_STORAGE_CONNECTION_STRING_1="_plaintext_"
declare -x CHECKPOINT_STORAGE_CONNECTION_STRING_2="_plaintext_"
declare -x CHECKPOINT_STORAGE_CONNECTION_STRING_3="_plaintext_"
declare -x CHECKPOINT_STORAGE_CONNECTION_STRING_4="_plaintext_"
declare -x CHECKPOINT_STORAGE_CONNECTION_STRING_5="_plaintext_"
declare -x CHECKPOINT_STORAGE_CONNECTION_STRING_6="_plaintext_"
declare -x CHECKPOINT_STORAGE_CONNECTION_STRING_7="_plaintext_"
declare -x CLASSPATH="/opt/microsoft/singularity/*"
declare -x CODE_MOUNT_OPTIONS=""
declare -x CODE_MOUNT_PATH="/scratch/workspaceblobstore/"
declare -x CODE_MOUNT_PERMISSIONS="RW"
declare -x CODE_PACKAGE_NAME="Job"
declare -x CODE_STORAGE_ACCOUNT_AUTH_PRINCIPAL_ID="780cb0c4-18a1-4be3-922b-a66f484d1557"
declare -x CODE_STORAGE_ACCOUNT_AUTH_TYPE="UserAssignedIdentity"
declare -x CODE_STORAGE_ACCOUNT_KEY="_plaintext_"
declare -x CODE_STORAGE_ACCOUNT_NAME="msrashamlws4466460092"
declare -x CODE_STORAGE_ACCOUNT_RESOURCE_ID=""
declare -x CODE_STORAGE_BLOB_NAME=""
declare -x CODE_STORAGE_ENDPOINT="msrashamlws4466460092.blob.core.windows.net"
declare -x CODE_STORAGE_KIND="AzureBlobStorage"
declare -x CODE_STORAGE_NAME="azureml-blobstore-dc1bc560-c630-4be6-bdf3-67e1367437d9"
declare -x CONDA_DEFAULT_ENV="ptca"
declare -x CONDA_ENVIRONMENT_PATH="/opt/conda/envs/ptca"
declare -x CONDA_PLUGINS_AUTO_ACCEPT_TOS="true"
declare -x CONDA_PREFIX="/opt/conda/envs/ptca"
declare -x CONTAINER_IMAGE="20251218T130926693"
declare -x CONTAINER_IMAGE_NAME="aiscofficialameacr.azurecr.io/base/job/pytorch/acpt-torch2.7.1-py3.10-cuda12.6-ubuntu22.04:20251218T130926693"
declare -x CONTAINER_KIND="lnxdocker"
declare -x CONTAINER_MEMORY_MB="835584"
declare -x CONTAINER_NAME="aiscofficialameacr.azurecr.io/base/job/pytorch/acpt-torch2.7.1-py3.10-cuda12.6-ubuntu22.04"
declare -x CONTAINER_SSH_PRIVATE_KEY="-----BEGIN RSA PRIVATE KEY-----
MIIEpQIBAAKCAQEA0lYtEQ2olcpbw6aCxW6BuvbqjHbFy37p1n+GE2paP8VoAlmZ
EtbPEcjys/szJT+MGLCqm5L2mMHJonc1kh/qRkoBhUznDJ+R62iU08Msd0zYH91S
PwOlL18nCrd/BaYdjs8B73hbf/ZdCnHpwcX1IEyFx0AYfhJcvwi3AERlc1FvUSPs
zda3uYU0QedPnpM0QmTHrYQWXhti1CEA1iSJSX1gPBIU0JaXMt0YYl+Nj2jybcVT
9/L06vl2AfRjlMck4fHBPcOuhsIWmTosufoGATvre3aXale/AeeQBMzK9+7atlVc
C0zu/Q+v38rKTWyKB0YFxgtiiEDsW/XbNhDrCQIDAQABAoIBAQDJQqYqvCwE8DUw
F8LnkV7W/G7f6sJGfnDXyvwK1ef3PzfPj9YVna9TcDkzmHiO+qhd86W76TrGXh9G
stRyttEfYq7j0vr+LC2e2FoX6phAqyneC5MoMp+7nUupSH1ldVaxEEjk0ACVh7Ht
TaSDwpxTxIT5a85Dy+Qs8vTQb6G3XYdA8oGFGkjAURQ+CX1TKTfDhuTHiPUMGsOQ
H2fab9RopbiaP70qEG+pyTRRVl7F4T02wK4oEUj99HyGfWGqoOg/CdsI+Pd0kuOl
VFQ0gKdD9vbQKuO1IBb+xedZFYTPXMgTogMoi1hL3Wc6XiQvru8hNVX/MAqJOx3V
AEwz9NslAoGBAPFNEpqmEHV83VokPGbCgjvsgNBZPej4BPmECa/VShz0pKA2YbPM
X4V+L6mNxFJbPVuF2BcxlYxi0DyuqpkfhzK8Ef5WRFbWLg+zxs1Nmb1PghX5Ogzo
9DZkpzvNJ7eC3NrvF8SB4iGS83kGiEd+1R9DuCxUdkrrQi6C4z5cujy3AoGBAN8m
O9tp57wOTBYyAcja/pd1VYo25QC4p2B+1YeLTaPSIzPz8AJEFchl690mUNvMXDSu
PEKB7Cje6b7a4Cvz3qGhyxigSwid1bLjik0WDBlFaosgt/NxL9FmJe2M6Mg9kovh
/vYeUqj4c2BIB1wLum2Td1nJWDWPbUEtNqWRXdY/AoGAXlHDEOISkuoA1+hMF9q1
71htrYMEmRjBUQrUgn97nb/ezaUUIaSkPdjqJnt8nrh9TlYN9lryWtKRFPctRfc1
8JXk7qanxc2oaYjbD4riqkX20kH99+fi9ZP4bn6tpKSpUYadorkmO/tl4gu0n0Wr
ZrIgvmsxZe15jBarXsf+IBcCgYEAnMNnWYTU3y/ME+udhVUTdaNgLHDT/+W47/kq
WMZsDKIbSOwdt/nMs7OmNv4r3715KSkd/Dr5hNzUqNdqlHYF+NaIrwwsqij3b2ya
Q/0xEq/JYWPi1oq1ZQ21p2RORB29Tbe+PXif6URhCUqQoQE8Pq5SMilYZogT4K26
riWpHlECgYEAuOoAIqZ4ZLhtQE2WaqPc0vAwIl2YG9trbNoH4+RjZxMK/7gnRAwl
H98hWnDUDx37RYUhXdHU7/G8ypQwOQ/VHKG2RStiDCk1zae1y4uUoJ6eHt8mSExK
u8Cdg42EArR542GmDZ6WtgU0aQSEBXWcF6875KR198/w2lO8WGLkdOs=
-----END RSA PRIVATE KEY-----
"
declare -x CONTAINER_SSH_PUBLIC_KEY="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDSVi0RDaiVylvDpoLFboG69uqMdsXLfunWf4YTalo/xWgCWZkS1s8RyPKz+zMlP4wYsKqbkvaYwcmidzWSH+pGSgGFTOcMn5HraJTTwyx3TNgf3VI/A6UvXycKt38Fph2OzwHveFt/9l0KcenBxfUgTIXHQBh+Ely/CLcARGVzUW9RI+zN1re5hTRB50+ekzRCZMethBZeG2LUIQDWJIlJfWA8EhTQlpcy3RhiX42PaPJtxVP38vTq+XYB9GOUxyTh8cE9w66GwhaZOiy5+gYBO+t7dpdqV78B55AEzMr37tq2VVwLTO79D6/fyspNbIoHRgXGC2KIQOxb9ds2EOsJ generated-key"
declare -x CUDA_VERSION="12.6.3"
declare -x CUSTOM_ENDPOINT1_FULL_PATH="/2dcef2e0-136e-4db5-a481-e79a93b7cce6/node-0/endpoint1"
declare -x CUSTOM_ENDPOINT1_PATH="endpoint1"
declare -x CUSTOM_ENDPOINT1_PORT="8081"
declare -x CUSTOM_ENDPOINT2_FULL_PATH="/2dcef2e0-136e-4db5-a481-e79a93b7cce6/node-0/endpoint2"
declare -x CUSTOM_ENDPOINT2_PATH="endpoint2"
declare -x CUSTOM_ENDPOINT2_PORT="8082"
declare -x CUSTOM_ENDPOINT3_FULL_PATH="/2dcef2e0-136e-4db5-a481-e79a93b7cce6/node-0/endpoint3"
declare -x CUSTOM_ENDPOINT3_PATH="endpoint3"
declare -x CUSTOM_ENDPOINT3_PORT="8083"
declare -x CUSTOM_ENDPOINT4_FULL_PATH="/2dcef2e0-136e-4db5-a481-e79a93b7cce6/node-0/endpoint4"
declare -x CUSTOM_ENDPOINT4_PATH="endpoint4"
declare -x CUSTOM_ENDPOINT4_PORT="8084"
declare -x CUSTOM_ENDPOINT5_FULL_PATH="/2dcef2e0-136e-4db5-a481-e79a93b7cce6/node-0/endpoint5"
declare -x CUSTOM_ENDPOINT5_PATH="endpoint5"
declare -x CUSTOM_ENDPOINT5_PORT="8085"
declare -x CUSTOM_PROM_ENDPOINT="https://westus2.api.azureml.ms/metric/v2.0/subscriptions/c4c534bc-9978-4974-9c87-551f7c5754ef/resourceGroups/msra-sh-aml-rg/providers/Microsoft.MachineLearningServices/workspaces/msra-sh-aml-ws/api/2.0/prometheus/post"
declare -x CUSTOM_PROM_TOKEN_REFRESH_INTERVAL_IN_SECONDS="2700"
declare -x CUSTOM_PROM_WRITE_RELABEL_CONFIG="    - source_labels: [minor_number,unique_label_name]
      action: replace
      target_label: DeviceId
      regex: (.+);unique_label_value
    - source_labels: [gpu_id,unique_label_name]
      action: replace
      target_label: DeviceId
      regex: (.+);unique_label_value
    - source_labels: [unique_label_name]
      action: replace
      target_label: azureml_metric_storage
      regex: unique_label_value
      replacement: 1
    - source_labels: [unique_label_name]
      action: replace
      target_label: azureml_metric_namespace
      regex: unique_label_value
      replacement: vienna
    - source_labels: [unique_label_name]
      action: replace
      target_label: azureml_resourceid
      regex: unique_label_value
      replacement: /subscriptions/c4c534bc-9978-4974-9c87-551f7c5754ef/resourceGroups/msra-sh-aml-rg/providers/Microsoft.MachineLearningServices/workspaces/msra-sh-aml-ws
    - source_labels: [unique_label_name]
      action: replace
      target_label: runId
      regex: unique_label_value
      replacement: helpful_shampoo_mj0cvl4kcg
    - source_labels: [unique_label_name]
      action: replace
      target_label: ComputeName
      regex: unique_label_value
      replacement: msrresrchvc
    - source_labels: [unique_label_name]
      action: keep
      regex: unique_label_value
    - source_labels: [instance,unique_label_name]
      action: replace
      target_label: InstanceId
      regex: (.+);unique_label_value
    - source_labels: [__name__]
      action: replace
      target_label: rootRunId
      regex: GpuEnergyJoules
      replacement: helpful_shampoo_mj0cvl4kcg
    - source_labels: [device,unique_label_name]
      action: replace
      target_label: DeviceId
      regex: (.+);unique_label_value"
declare -x DATA="/datasets/"
declare -x DATASET_ENABLE_CLEX_FALLBACK="true"
declare -x DATASET_MOUNT_BLOCK_BASED_CACHE_ENABLED="false"
declare -x DATASET_MOUNT_BLOCK_FILE_CACHE_WRITE_THREADS="184"
declare -x DATASET_MOUNT_DISK_RESOURCES="/scratch:3072 GB"
declare -x DATASET_MOUNT_READ_THREADS="368"
declare -x DATASET_RSLEX_UPLOAD="true"
declare -x DEBIAN_FRONTEND="noninteractive"
declare -x DEBUG_CONTAINER_HOLD=""
declare -x DISTRIBUTED_BACKEND="nccl"
declare -x DLTS_JOB_ID="2dcef2e0-136e-4db5-a481-e79a93b7cce6"
declare -x DLTS_NUM_GPU_PER_WORKER="4"
declare -x DLTS_NUM_WORKER="1"
declare -x DLTS_ROLE_IDX="0"
declare -x DLTS_ROLE_NAME="master"
declare -x DLWS_JOB_ID="2dcef2e0-136e-4db5-a481-e79a93b7cce6"
declare -x DLWS_NUM_GPU_PER_WORKER="4"
declare -x DLWS_NUM_WORKER="1"
declare -x DLWS_ROLE_IDX="0"
declare -x DLWS_ROLE_NAME="master"
declare -x DNSMASQ_READY_POLL_DELAY_IN_SECONDS="1"
declare -x DOTNET_SYSTEM_GLOBALIZATION_INVARIANT="1"
declare -x DPREP_RSLEX_LOG_STDOUT="true"
declare -x DPREP_RSLEX_LOG_STDOUT_SCRUBBED="true"
declare -x DSVM="False"
declare -x ENABLE_MANAGED_EXECUTION="false"
declare -x ENABLE_NETWORK_TROUBLESHOOTING="true"
declare -x ENABLE_NOTEBOOK="true"
declare -x ENABLE_SIDECAR="true"
declare -x ENABLE_SSH="true"
declare -x ENABLE_TENSORBOARD="false"
declare -x ENABLE_VALIDATOR="false"
declare -x ENDPOINT__CUSTOM_ENDPOINT1_PORT=""
declare -x ENDPOINT__CUSTOM_ENDPOINT2_PORT=""
declare -x ENDPOINT__CUSTOM_ENDPOINT3_PORT=""
declare -x ENDPOINT__CUSTOM_ENDPOINT4_PORT=""
declare -x ENDPOINT__CUSTOM_ENDPOINT5_PORT=""
declare -x ENDPOINT__MASTER_PORT=""
declare -x ENDPOINT__METRICS_EXPORTER_PORT=""
declare -x ENDPOINT__NOTEBOOK_PORT=""
declare -x ENDPOINT__SIDECAR_SSH_PORT=""
declare -x ENDPOINT__SSH_PORT=""
declare -x ENDPOINT__TENSORBOARD_PORT=""
declare -x ENDPOINT__USER_NODE_AGENT_PORT=""
declare -x EXECUTE_CMD="YgBhAHMAaAA="
declare -x EXECUTE_CMD_ARGS="LQBjACAAIgBpAD0AMAA7ACAAdwBoAGkAbABlACAAWwAgAFwAJABpACAALQBsAHQAIAAyADAAMAAwACAAXQA7ACAAZABvACAAaQBmACAAWwAgAC0AZgAgAC8AcwBjAHIAYQB0AGMAaAAvAGEAegB1AHIAZQBtAGwALwBjAHIALwBzAHQAYQByAHQAcgB1AG4ALgBiAGEAcwBoACAAXQA7ACAAdABoAGUAbgAgAGUAYwBoAG8AIABcACIAWwBDAG8AbQBtAG8AbgBSAHUAbgB0AGkAbQBlAF0AIABTAHQAYQByAHQAcgB1AG4AIABzAGMAcgBpAHAAdAAgAGkAcwAgAHIAZQBhAGQAeQAuACAAUwB0AGEAcgB0AGkAbgBnACAAcgB1AG4AIAAuAC4ALgBcACIAOwAgAC8AcwBjAHIAYQB0AGMAaAAvAGEAegB1AHIAZQBtAGwALwBjAHIALwBzAHQAYQByAHQAcgB1AG4ALgBiAGEAcwBoACAALwBzAGMAcgBhAHQAYwBoAC8AYQB6AHUAcgBlAG0AbAAvAGMAcgAgADEAOwAgAGUAeABpAHQAIABcACQAPwA7ACAAZQBsAHMAZQAgAHMAbABlAGUAcAAgADAALgA1ADsAIAAoACgAaQArACsAKQApADsAIABmAGkAOwAgAGQAbwBuAGUAOwAgAGUAYwBoAG8AIABcACIAWwBDAG8AbQBtAG8AbgBSAHUAbgB0AGkAbQBlAF0AIABGAGEAaQBsAGUAZAAgAHQAbwAgAHMAdABhAHIAdAAgAHIAdQBuAFwAIgA7ACAAZQB4AGkAdAAgADEAMAAwACIA"
declare -x EXIT_USER_NODE_AGENT_ON_WORKER_EXIT="false"
declare -x Fabric_Application_Name="2dcef2e0-136e-4db5-a481-e79a93b7cce6"
declare -x Fabric_Id="00000000-0000-0000-0000-000000000000"
declare -x Fabric_Service_Name="fabric:/2dcef2e0-136e-4db5-a481-e79a93b7cce6/node-0"
declare -x GLOO_SOCKET_IFNAME="eth0"
declare -x GPU_PER_NODE_COUNT="4"
declare -x GPU_TYPE="cu126"
declare -x HOME="/home/aiscuser"
declare -x HOSTNAME="node-0"
declare -x HOST_APIPA_IP=""
declare -x HWLOC_COMPONENTS="-gl"
declare -x IDENTITY_HEADER="sv=1.0&st=2026-03-16T16%3a51%3a44Z&se=9999-12-31T23%3a59%3a59Z&sr=eyIkaWQiOiIxIiwiUmVzb3VyY2VUeXBlIjoiSm9iIiwiUmVzb3VyY2VJZCI6Ii9zdWJzY3JpcHRpb25zL2JhNzA5Y2E1LTFhMmMtNDc5Yy1hMWNiLTZlMDM0NmI4MWJmMS9yZXNvdXJjZWdyb3Vwcy9zaW5ndWxhcml0eWhvYm8vcHJvdmlkZXJzL01pY3Jvc29mdC5TaW5ndWxhcml0eS9hY2NvdW50cy9tc3JyZXNyY2h2Yy9qb2JzL2hlbHBmdWxfc2hhbXBvb19tajBjdmw0a2NnIiwiRmVkZXJhdGlvbklkIjp7IiRpZCI6IjIiLCJMb2NhdGlvbiI6Indlc3R1czIiLCJOYW1lIjoiYXptbC1wcm9kLXdlc3R1czItYXpodWItMTMifX0&spr=ssh&sig=2d5ErFxvCZR6ncb7CzB6zdisufFCccMCWBMQ5Vktt1Q%3d"
declare -x IDENTITY_LIST="780cb0c4-18a1-4be3-922b-a66f484d1557"
declare -x IDENTITY_MNGT_RESOURCE="https://management.azure.com/"
declare -x IDENTITY_MOUNT_RETRY_MIN="15"
declare -x IDENTITY_PORT="8084"
declare -x IDENTITY_SERVICE_HOST="tokenproxyagentservice.tokenproxyagentlnxapp"
declare -x INFINIBAND_INTERFACE_ID=""
declare -x INPUT="/blob/"
declare -x INPUT1_MOUNT_OPTIONS=""
declare -x INPUT1_MOUNT_PATH="/var/data/input1"
declare -x INPUT1_MOUNT_PERMISSIONS="MustSpecifyViaApplicationParameters"
declare -x INPUT1_STORAGE_ACCOUNT_AUTH_PRINCIPAL_ID="MustSpecifyViaApplicationParameters"
declare -x INPUT1_STORAGE_ACCOUNT_AUTH_TYPE="MustSpecifyViaApplicationParameters"
declare -x INPUT1_STORAGE_ACCOUNT_KEY="_plaintext_"
declare -x INPUT1_STORAGE_ACCOUNT_NAME="MustSpecifyViaApplicationParameters"
declare -x INPUT1_STORAGE_ACCOUNT_RESOURCE_ID="MustSpecifyViaApplicationParameters"
declare -x INPUT1_STORAGE_BLOB_NAME="MustSpecifyViaApplicationParameters"
declare -x INPUT1_STORAGE_ENDPOINT="MustSpecifyViaApplicationParameters"
declare -x INPUT1_STORAGE_KIND="None"
declare -x INPUT1_STORAGE_NAME="MustSpecifyViaApplicationParameters"
declare -x INPUT2_MOUNT_OPTIONS=""
declare -x INPUT2_MOUNT_PATH="/var/data/input2"
declare -x INPUT2_MOUNT_PERMISSIONS="MustSpecifyViaApplicationParameters"
declare -x INPUT2_STORAGE_ACCOUNT_AUTH_PRINCIPAL_ID="MustSpecifyViaApplicationParameters"
declare -x INPUT2_STORAGE_ACCOUNT_AUTH_TYPE="MustSpecifyViaApplicationParameters"
declare -x INPUT2_STORAGE_ACCOUNT_KEY="_plaintext_"
declare -x INPUT2_STORAGE_ACCOUNT_NAME="MustSpecifyViaApplicationParameters"
declare -x INPUT2_STORAGE_ACCOUNT_RESOURCE_ID="MustSpecifyViaApplicationParameters"
declare -x INPUT2_STORAGE_BLOB_NAME="MustSpecifyViaApplicationParameters"
declare -x INPUT2_STORAGE_ENDPOINT="MustSpecifyViaApplicationParameters"
declare -x INPUT2_STORAGE_KIND="None"
declare -x INPUT2_STORAGE_NAME="MustSpecifyViaApplicationParameters"
declare -x INPUT3_MOUNT_OPTIONS=""
declare -x INPUT3_MOUNT_PATH="/var/data/input3"
declare -x INPUT3_MOUNT_PERMISSIONS="MustSpecifyViaApplicationParameters"
declare -x INPUT3_STORAGE_ACCOUNT_AUTH_PRINCIPAL_ID="MustSpecifyViaApplicationParameters"
declare -x INPUT3_STORAGE_ACCOUNT_AUTH_TYPE="MustSpecifyViaApplicationParameters"
declare -x INPUT3_STORAGE_ACCOUNT_KEY="_plaintext_"
declare -x INPUT3_STORAGE_ACCOUNT_NAME="MustSpecifyViaApplicationParameters"
declare -x INPUT3_STORAGE_ACCOUNT_RESOURCE_ID="MustSpecifyViaApplicationParameters"
declare -x INPUT3_STORAGE_BLOB_NAME="MustSpecifyViaApplicationParameters"
declare -x INPUT3_STORAGE_ENDPOINT="MustSpecifyViaApplicationParameters"
declare -x INPUT3_STORAGE_KIND="None"
declare -x INPUT3_STORAGE_NAME="MustSpecifyViaApplicationParameters"
declare -x INPUT4_MOUNT_OPTIONS=""
declare -x INPUT4_MOUNT_PATH="/var/data/input4"
declare -x INPUT4_MOUNT_PERMISSIONS="MustSpecifyViaApplicationParameters"
declare -x INPUT4_STORAGE_ACCOUNT_AUTH_PRINCIPAL_ID="MustSpecifyViaApplicationParameters"
declare -x INPUT4_STORAGE_ACCOUNT_AUTH_TYPE="MustSpecifyViaApplicationParameters"
declare -x INPUT4_STORAGE_ACCOUNT_KEY="_plaintext_"
declare -x INPUT4_STORAGE_ACCOUNT_NAME="MustSpecifyViaApplicationParameters"
declare -x INPUT4_STORAGE_ACCOUNT_RESOURCE_ID="MustSpecifyViaApplicationParameters"
declare -x INPUT4_STORAGE_BLOB_NAME="MustSpecifyViaApplicationParameters"
declare -x INPUT4_STORAGE_ENDPOINT="MustSpecifyViaApplicationParameters"
declare -x INPUT4_STORAGE_KIND="None"
declare -x INPUT4_STORAGE_NAME="MustSpecifyViaApplicationParameters"
declare -x INPUT5_MOUNT_OPTIONS=""
declare -x INPUT5_MOUNT_PATH="/var/data/input5"
declare -x INPUT5_MOUNT_PERMISSIONS="MustSpecifyViaApplicationParameters"
declare -x INPUT5_STORAGE_ACCOUNT_AUTH_PRINCIPAL_ID="MustSpecifyViaApplicationParameters"
declare -x INPUT5_STORAGE_ACCOUNT_AUTH_TYPE="MustSpecifyViaApplicationParameters"
declare -x INPUT5_STORAGE_ACCOUNT_KEY="_plaintext_"
declare -x INPUT5_STORAGE_ACCOUNT_NAME="MustSpecifyViaApplicationParameters"
declare -x INPUT5_STORAGE_ACCOUNT_RESOURCE_ID="MustSpecifyViaApplicationParameters"
declare -x INPUT5_STORAGE_BLOB_NAME="MustSpecifyViaApplicationParameters"
declare -x INPUT5_STORAGE_ENDPOINT="MustSpecifyViaApplicationParameters"
declare -x INPUT5_STORAGE_KIND="None"
declare -x INPUT5_STORAGE_NAME="MustSpecifyViaApplicationParameters"
declare -x INTERNAL_OR_PUBLIC="public"
declare -x JOB_EXECUTION_MODE="Basic"
declare -x JOB_WAIT_AFTER="10"
declare -x K8_ENABLE_USER_NODE_AGENT_REGISTRATION="false"
declare -x KUBERNETES_POD_IP="100.64.73.58"
declare -x KUBERNETES_POD_NAME="node-0-5mrn4"
declare -x KUBERNETES_POD_NAMESPACE="2dcef2e0-136e-4db5-a481-e79a93b7cce6"
declare -x KUBERNETES_POD_UID="3ba68d66-6f65-4e69-ad94-26cc0e413a72"
declare -x KUBERNETES_PORT="tcp://10.0.0.1:443"
declare -x KUBERNETES_PORT_443_TCP="tcp://10.0.0.1:443"
declare -x KUBERNETES_PORT_443_TCP_ADDR="10.0.0.1"
declare -x KUBERNETES_PORT_443_TCP_PORT="443"
declare -x KUBERNETES_PORT_443_TCP_PROTO="tcp"
declare -x KUBERNETES_SERVICE_HOST="10.0.0.1"
declare -x KUBERNETES_SERVICE_PORT="443"
declare -x KUBERNETES_SERVICE_PORT_HTTPS="443"
declare -x LANG="en_US.UTF-8"
declare -x LD_LIBRARY_PATH="/opt/hpcx/nccl_rdma_sharp_plugin/lib:/opt/nccl-rdma-sharp-plugins/lib:/opt/hpcx/ompi/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64"
declare -x LIBRARY_PATH="/usr/local/cuda/lib64/stubs"
declare -x LTL_AGENT_PORT="9019"
declare -x MASTER_ADDR="node-0"
declare -x MASTER_PORT="9500"
declare -x METRICS_EXPORTER_PORT="10006"
declare -x METRICS_EXPORTER_RUNNING_CONTEXT="user_node"
declare -x MLFLOW_DISABLE_ENV_MANAGER_CONDA_WARNING="True"
declare -x MLFLOW_EXPERIMENT_ID="8ddba47b-5442-4000-8bd2-be558857ecce"
declare -x MLFLOW_EXPERIMENT_NAME="vllm-sh-gcr12301-abd9158f"
declare -x MLFLOW_RUN_ID="helpful_shampoo_mj0cvl4kcg"
declare -x MLFLOW_TRACKING_TOKEN="eyJhbGciOiJSUzI1NiIsImtpZCI6IjhDMTAzQTRDMEI3QTAxQzQyOTE3QTlBMzVCRjJEMkE2NEQyMTI2NDAiLCJ0eXAiOiJKV1QifQ.eyJyb2xlIjoiQ29udHJpYnV0b3IiLCJzY29wZSI6Ii9zdWJzY3JpcHRpb25zL2M0YzUzNGJjLTk5NzgtNDk3NC05Yzg3LTU1MWY3YzU3NTRlZi9yZXNvdXJjZUdyb3Vwcy9tc3JhLXNoLWFtbC1yZy9wcm92aWRlcnMvTWljcm9zb2Z0Lk1hY2hpbmVMZWFybmluZ1NlcnZpY2VzL3dvcmtzcGFjZXMvbXNyYS1zaC1hbWwtd3MiLCJhY2NvdW50aWQiOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDAiLCJ3b3Jrc3BhY2VJZCI6ImRjMWJjNTYwLWM2MzAtNGJlNi1iZGYzLTY3ZTEzNjc0MzdkOSIsInByb2plY3RpZCI6IjAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDAwMCIsImRpc2NvdmVyeSI6InVyaTovL2Rpc2NvdmVyeXVyaS8iLCJ0aWQiOiI3MmY5ODhiZi04NmYxLTQxYWYtOTFhYi0yZDdjZDAxMWRiNDciLCJvaWQiOiI4YTU4OTcyNS03NjIyLTQxZGEtODE4Mi04ZGE4MTEyN2RkNzIiLCJwdWlkIjoiMTAwMzIwMDM4RDM0MEUzMyIsImlzcyI6ImF6dXJlbWwiLCJhcHBpZCI6IllpZmFuIFlhbmcgKFNDLUFMVCkiLCJleHAiOjE3NzUyNDU2NzMsImF1ZCI6ImF6dXJlbWwifQ.qUNWzCsOQRImJaPHTy0Eca0xKbpLQgBsEMpcww7A7VKx_8u848jo6sWbSlWOBCRsvwpe56LkSVtHiqrKsV_tllYNi5vc9WJAdpA6m6t9Arp-Eym8ZLvgeZKspoALHsYHKad31quNgC_AGLebrMnisQoWa98aLpvYyjHm2P8evuH9W2Gz__uLammX4C0OHuUI8sN1941NGtFyUhw9OnIemN3u_FipLKbk8yMAwmNPsDnlEpBtMuPEY0_GlmCrlryagWZsUkK6s5ntTfs8aZ4ZKfKPyRz4XHFYkWKbKBopNMfUdf9FsYDlaN66mDnBJv63ClYot5QjoGYsX-qH09suPw"
declare -x MLFLOW_TRACKING_URI="azureml://westus2.api.azureml.ms/mlflow/v1.0/subscriptions/c4c534bc-9978-4974-9c87-551f7c5754ef/resourceGroups/msra-sh-aml-rg/providers/Microsoft.MachineLearningServices/workspaces/msra-sh-aml-ws"
declare -x MSI_ENDPOINT="http://127.0.0.1:9138/metadata/managedidentity/oauth2/token"
declare -x MSI_SECRET="sv=1.0&st=2026-03-16T16%3a51%3a44Z&se=9999-12-31T23%3a59%3a59Z&sr=eyIkaWQiOiIxIiwiUmVzb3VyY2VUeXBlIjoiSm9iIiwiUmVzb3VyY2VJZCI6Ii9zdWJzY3JpcHRpb25zL2JhNzA5Y2E1LTFhMmMtNDc5Yy1hMWNiLTZlMDM0NmI4MWJmMS9yZXNvdXJjZWdyb3Vwcy9zaW5ndWxhcml0eWhvYm8vcHJvdmlkZXJzL01pY3Jvc29mdC5TaW5ndWxhcml0eS9hY2NvdW50cy9tc3JyZXNyY2h2Yy9qb2JzL2hlbHBmdWxfc2hhbXBvb19tajBjdmw0a2NnIiwiRmVkZXJhdGlvbklkIjp7IiRpZCI6IjIiLCJMb2NhdGlvbiI6Indlc3R1czIiLCJOYW1lIjoiYXptbC1wcm9kLXdlc3R1czItYXpodWItMTMifX0&spr=ssh&sig=2d5ErFxvCZR6ncb7CzB6zdisufFCccMCWBMQ5Vktt1Q%3d"
declare -x NCCL_ASYNC_ERROR_HANDLING="1"
declare -x NCCL_DEBUG="INFO"
declare -x NCCL_DEBUG_SUBSYS="INIT,GRAPH"
declare -x NCCL_IB_HCA=""
declare -x NCCL_SOCKET_IFNAME="eth0"
declare -x NCCL_VERSION="2.23.4-1"
declare -x NGINX_MSI_PORT="9138"
declare -x NODE_COUNT="1"
declare -x NODE_NAME="node-0"
declare -x NODE_RANK="0"
declare -x NOTEBOOK_PORT="8080"
declare -x NOTEBOOK_UI_PATH="notebook"
declare -x NPU_PER_NODE_COUNT="0"
declare -x NVARCH="x86_64"
declare -x NVIDIA_CTK_LIBCUDA_DIR="/usr/lib/x86_64-linux-gnu"
declare -x NVIDIA_DRIVER_CAPABILITIES="compute,utility"
declare -x NVIDIA_PRODUCT_NAME="CUDA"
declare -x NVIDIA_REQUIRE_CUDA="cuda>=12.6 brand=unknown,driver>=470,driver<471 brand=grid,driver>=470,driver<471 brand=tesla,driver>=470,driver<471 brand=nvidia,driver>=470,driver<471 brand=quadro,driver>=470,driver<471 brand=quadrortx,driver>=470,driver<471 brand=nvidiartx,driver>=470,driver<471 brand=vapps,driver>=470,driver<471 brand=vpc,driver>=470,driver<471 brand=vcs,driver>=470,driver<471 brand=vws,driver>=470,driver<471 brand=cloudgaming,driver>=470,driver<471 brand=unknown,driver>=535,driver<536 brand=grid,driver>=535,driver<536 brand=tesla,driver>=535,driver<536 brand=nvidia,driver>=535,driver<536 brand=quadro,driver>=535,driver<536 brand=quadrortx,driver>=535,driver<536 brand=nvidiartx,driver>=535,driver<536 brand=vapps,driver>=535,driver<536 brand=vpc,driver>=535,driver<536 brand=vcs,driver>=535,driver<536 brand=vws,driver>=535,driver<536 brand=cloudgaming,driver>=535,driver<536 brand=unknown,driver>=550,driver<551 brand=grid,driver>=550,driver<551 brand=tesla,driver>=550,driver<551 brand=nvidia,driver>=550,driver<551 brand=quadro,driver>=550,driver<551 brand=quadrortx,driver>=550,driver<551 brand=nvidiartx,driver>=550,driver<551 brand=vapps,driver>=550,driver<551 brand=vpc,driver>=550,driver<551 brand=vcs,driver>=550,driver<551 brand=vws,driver>=550,driver<551 brand=cloudgaming,driver>=550,driver<551"
declare -x NVIDIA_VISIBLE_DEVICES="void"
declare -x NV_CUDA_CUDART_DEV_VERSION="12.6.77-1"
declare -x NV_CUDA_CUDART_VERSION="12.6.77-1"
declare -x NV_CUDA_LIB_VERSION="12.6.3-1"
declare -x NV_CUDA_NSIGHT_COMPUTE_DEV_PACKAGE="cuda-nsight-compute-12-6=12.6.3-1"
declare -x NV_CUDA_NSIGHT_COMPUTE_VERSION="12.6.3-1"
declare -x NV_LIBCUBLAS_DEV_PACKAGE="libcublas-dev-12-6=12.6.4.1-1"
declare -x NV_LIBCUBLAS_DEV_PACKAGE_NAME="libcublas-dev-12-6"
declare -x NV_LIBCUBLAS_DEV_VERSION="12.6.4.1-1"
declare -x NV_LIBCUBLAS_PACKAGE="libcublas-12-6=12.6.4.1-1"
declare -x NV_LIBCUBLAS_PACKAGE_NAME="libcublas-12-6"
declare -x NV_LIBCUBLAS_VERSION="12.6.4.1-1"
declare -x NV_LIBCUSPARSE_DEV_VERSION="12.5.4.2-1"
declare -x NV_LIBCUSPARSE_VERSION="12.5.4.2-1"
declare -x NV_LIBNCCL_DEV_PACKAGE="libnccl-dev=2.23.4-1+cuda12.6"
declare -x NV_LIBNCCL_DEV_PACKAGE_NAME="libnccl-dev"
declare -x NV_LIBNCCL_DEV_PACKAGE_VERSION="2.23.4-1"
declare -x NV_LIBNCCL_PACKAGE="libnccl2=2.23.4-1+cuda12.6"
declare -x NV_LIBNCCL_PACKAGE_NAME="libnccl2"
declare -x NV_LIBNCCL_PACKAGE_VERSION="2.23.4-1"
declare -x NV_LIBNPP_DEV_PACKAGE="libnpp-dev-12-6=12.3.1.54-1"
declare -x NV_LIBNPP_DEV_VERSION="12.3.1.54-1"
declare -x NV_LIBNPP_PACKAGE="libnpp-12-6=12.3.1.54-1"
declare -x NV_LIBNPP_VERSION="12.3.1.54-1"
declare -x NV_NVML_DEV_VERSION="12.6.77-1"
declare -x NV_NVPROF_DEV_PACKAGE="cuda-nvprof-12-6=12.6.80-1"
declare -x NV_NVPROF_VERSION="12.6.80-1"
declare -x NV_NVTX_VERSION="12.6.77-1"
declare -x OLDPWD
declare -x OPAL_PREFIX="/opt/hpcx/ompi"
declare -x OS_TYPE="ubuntu2204"
declare -x OUTPUT="/output/"
declare -x OUTPUT_MOUNT_OPTIONS=""
declare -x OUTPUT_MOUNT_PATH="/var/data/output"
declare -x OUTPUT_MOUNT_PERMISSIONS="MustSpecifyViaApplicationParameters"
declare -x OUTPUT_STORAGE_ACCOUNT_AUTH_PRINCIPAL_ID="MustSpecifyViaApplicationParameters"
declare -x OUTPUT_STORAGE_ACCOUNT_AUTH_TYPE="MustSpecifyViaApplicationParameters"
declare -x OUTPUT_STORAGE_ACCOUNT_KEY="_plaintext_"
declare -x OUTPUT_STORAGE_ACCOUNT_NAME="MustSpecifyViaApplicationParameters"
declare -x OUTPUT_STORAGE_ACCOUNT_RESOURCE_ID="MustSpecifyViaApplicationParameters"
declare -x OUTPUT_STORAGE_BLOB_NAME="MustSpecifyViaApplicationParameters"
declare -x OUTPUT_STORAGE_ENDPOINT="MustSpecifyViaApplicationParameters"
declare -x OUTPUT_STORAGE_KIND="None"
declare -x OUTPUT_STORAGE_NAME="MustSpecifyViaApplicationParameters"
declare -x PATH="/usr/local/mpi/bin:/usr/local/ucx/bin:/opt/conda/envs/ptca/bin:/opt/conda/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
declare -x PROCESS_ACTIVITY_EXPORTER_PROMETHEUS_PORT="10008"
declare -x PWD="/scratch/azureml/cr/j/b5e4aee59bb6481db8ad5d94681dd957/exe/wd"
declare -x PYTHON_VERSION="3.10"
declare -x PYTORCH_BUILD_VERSION="2.7.1"
declare -x PYTORCH_TYPE="stable"
declare -x RANK="0"
declare -x REGISTRATION_MESSAGE_FAILURE_SHOULD_RESTART_CONTAINER="true"
declare -x REGISTRATION_MESSAGE_MAX_TIMEOUT_IN_SEC="1200"
declare -x REGISTRATION_MESSAGE_STARTING_RETRY_DELAY_IN_MILLISECONDS="200"
declare -x RSLEX_DOWNLOADER_THREADS="368"
declare -x RSLEX_THREAD_COUNT="92"
declare -x SAS_URL_FOR_BLOB_LEASE="https://msrashamlws4466460092.blob.core.windows.net/azureml-blobstore-dc1bc560-c630-4be6-bdf3-67e1367437d9/azureml/helpful_shampoo_mj0cvl4kcg/LeaseBlob_?sv=2019-07-07&sr=c&sig=NEnwpJcTPYHn7dC%2BTyen1XW8inBVJkF05Iy0%2FfNq5d0%3D&skoid=780cb0c4-18a1-4be3-922b-a66f484d1557&sktid=72f988bf-86f1-41af-91ab-2d7cd011db47&skt=2026-03-13T17%3A05%3A49Z&ske=2026-03-20T17%3A05%3A49Z&sks=b&skv=2019-07-07&st=2026-03-13T17%3A37%3A57Z&se=2026-03-20T16%3A55%3A49Z&sp=rcwl"
declare -x SERVICE_ROOTPATH="__ServiceName__"
declare -x SHARED_MEMORY_PERCENT="0.50"
declare -x SHLVL="5"
declare -x SIDECAR_SSH_PORT="2424"
declare -x SIDECAR_START_SCRIPT="/opt/microsoft/azureml/sidecarrun.bash"
declare -x SINGULARITY_BASE_IMAGE="base/job/pytorch/acpt-torch2.7.1-py3.10-cuda12.6-ubuntu22.04:20260119T230153663"
declare -x SINGULARITY_BOOTSTRAP_TIMEOUT_IN_MINUTES="60"
declare -x SINGULARITY_CHECKPOINT_RESTORE_STRATEGY_TYPE="\$(SINGULARITY_CHECKPOINT_RESTORE_STRATEGY_TYPE)"
declare -x SINGULARITY_CONTAINER_CPU_PERCENT_LIMIT="98"
declare -x SINGULARITY_CONTAINER_NAME="Job"
declare -x SINGULARITY_CPU_CORES="92"
declare -x SINGULARITY_DATA_HOME="/var/data/microsoft/singularity"
declare -x SINGULARITY_DEPLOYMENT_MANAGER="Coordinator"
declare -x SINGULARITY_DISABLE_CUDA_COMPAT_LIBRARY_REMOVAL="false"
declare -x SINGULARITY_DISABLE_FATAL_ONGOING_SSH_CHECK_FAIL="true"
declare -x SINGULARITY_DISABLE_IPOIB_PROJECTION="true"
declare -x SINGULARITY_ENABLE_DISTRIBUTED_DEDUP="false"
declare -x SINGULARITY_ENABLE_EVENT_PUBLISHING="true"
declare -x SINGULARITY_ENABLE_PREEMPTION_SIGNAL="false"
declare -x SINGULARITY_ENABLE_PROCESS_ACTIVITY_MONITOR="false"
declare -x SINGULARITY_ENABLE_PROCESS_RESOURCE_EXPORTER="false"
declare -x SINGULARITY_ENABLE_TRANSPARENT_CHECKPOINTING="false"
declare -x SINGULARITY_ENABLE_TRANSPARENT_ELASTICITY="false"
declare -x SINGULARITY_ETHERNET_INTERFACES="eth0"
declare -x SINGULARITY_EXIT_CODE_INTERPRETATION_ENABLED="True"
declare -x SINGULARITY_EXIT_ERROR_FILE_PATH="/_singularity_exit_data_\\exit_error"
declare -x SINGULARITY_FEDERATION_NAME="azml-prod-westus2-azhub-13"
declare -x SINGULARITY_HOME="/opt/microsoft/singularity"
declare -x SINGULARITY_IMAGE_ACCELERATOR="NVIDIA"
declare -x SINGULARITY_IMAGE_ACCELERATOR_SKU="A100"
declare -x SINGULARITY_IMAGE_FRAMEWORK="PYTORCH"
declare -x SINGULARITY_JOB="true"
declare -x SINGULARITY_JOB_KIND="distributed"
declare -x SINGULARITY_LFS_LOGDIR="/mnt/resource/singularity/criu/staging/LfsInterceptor/LfsInterceptorLog"
declare -x SINGULARITY_LOCAL_DATA_HOME="/var/local/data/microsoft/singularity"
declare -x SINGULARITY_LOCATION="westus2"
declare -x SINGULARITY_MEMORY_MB="835584"
declare -x SINGULARITY_MPICH_HOSTFILE_PATH="/home/aiscuser/hostfile.mpich"
declare -x SINGULARITY_MPI_ENV="--hostfile /home/aiscuser/hostfile -mca pml ob1 -mca btl ^openib -mca btl_tcp_if_include eth0 -mca oob_tcp_if_include eth0 -np 4"
declare -x SINGULARITY_MPI_HOSTFILE_PATH="/home/aiscuser/hostfile"
declare -x SINGULARITY_NETWORK_TYPE="Open"
declare -x SINGULARITY_NODENAME="nc96adsv40100000k"
declare -x SINGULARITY_POST_EXE_CMD=""
declare -x SINGULARITY_POST_EXE_CMD_ARGS=""
declare -x SINGULARITY_POST_EXE_CMD_TIMEOUT_IN_SECONDS="180"
declare -x SINGULARITY_PRE_EXE_CMD="ZQBjAGgAbwA="
declare -x SINGULARITY_PRE_EXE_CMD_ARGS="UwB0AGEAcgB0AGkAbgBnACAAQwBvAG0AbQBvAG4AIABSAHUAbgB0AGkAbQBlACAAagBvAGIAIAB3AGkAdABoACAAcwBpAGQAZQBjAGEAcgAgAG0AbwBkAGUAIABlAG4AYQBiAGwAZQBkAC4AIABTAGsAaQBwAHAAaQBuAGcAIABqAG8AYgAgAHAAcgBlAHAAYQByAGEAdABpAG8AbgAuAA=="
declare -x SINGULARITY_PRE_EXE_CMD_TIMEOUT_IN_SECONDS="180"
declare -x SINGULARITY_PROCESS_ACTIVITY_MONITOR_IDLE_DURATION_IN_SECONDS="1800"
declare -x SINGULARITY_RUN_GPU_HEALTHCHECK="true"
declare -x SINGULARITY_SIDECAR_CONSOLIDATION="true"
declare -x SINGULARITY_START_ENTRYPOINT_ON_ALL_NODES="false"
declare -x SINGULARITY_SYSTEM_SIDECAR_SSH_PORT="2434"
declare -x SINGULARITY_TRACE_CONFIG="{\"EnableTracing\":true,\"EnabledTracers\":[\"GlobalPerfTracer\"],\"SamplerTypeName\":\"Microsoft.Azure.AISC.Common.Tracing.TraceFlagBasedSampler, Microsoft.Azure.AISC.Diagnostics\"}"
declare -x SINGULARITY_TRACE_CONTEXT="{\"traceparent\":\"00-b9aa4a0471aba66922f5e21fb3a5d46a-4e22a14c8e5d8075-01\",\"baggage\":\"ResourceId=%2Fsubscriptions%2Fba709ca5-1a2c-479c-a1cb-6e0346b81bf1%2Fresourcegroups%2Fsingularityhobo%2Fproviders%2FMicrosoft.Singularity%2Faccounts%2Fmsrresrchvc%2Fjobs%2Fhelpful_shampoo_mj0cvl4kcg,ResourceInstanceId=2dcef2e0-136e-4db5-a481-e79a93b7cce6\"}"
declare -x SINGULARITY_USER_GROUP_ID="9000"
declare -x SINGULARITY_USER_GROUP_NAME="aiscuser"
declare -x SINGULARITY_USER_HOME="/home/aiscuser"
declare -x SINGULARITY_USER_ID="9000"
declare -x SINGULARITY_USER_NAME="aiscuser"
declare -x SINGULARITY_VALIDATION_OPTIONAL="true"
declare -x SINGULARITY_WAIT_RUN_WORKLOAD_APPROVAL="false"
declare -x SINGULARITY_WEB_SOCKETS_CAPABLE="true"
declare -x SINGULARITY_WEB_SOCKET_CLIENT_PING_INTERVAL_IN_SECONDS="30"
declare -x SINGULARITY_WEB_SOCKET_CLIENT_PING_TIMEOUT_IN_SECONDS="5"
declare -x SINGULARITY_WEB_SOCKET_KEEP_ALIVE_INTERVAL_IN_SECONDS="120"
declare -x SKIP_IMAGE_VALIDATION=""
declare -x SSH_CONNECTIVITY_RETRY_COUNT="31"
declare -x SSH_PORT="22"
declare -x SSL_CERT_FILE="/usr/lib/ssl/certs/ca-certificates.crt"
declare -x SUDO="sudo"
declare -x TENSORBOARD_LOG_DIR="/scratch/amlt_code/outputs"
declare -x TENSORBOARD_PORT="6066"
declare -x TENSORBOARD_UI_PATH="tensorboard"
declare -x TORCH_DISTRIBUTED_INIT_STORE_MOUNT_PATH="MustSpecifyViaApplicationParameters"
declare -x TORCH_DISTRIBUTED_INIT_STORE_MOUNT_PERMISSIONS="MustSpecifyViaApplicationParameters"
declare -x TORCH_DISTRIBUTED_INIT_STORE_STORAGE_ENDPOINT="MustSpecifyViaApplicationParameters"
declare -x TORCH_DISTRIBUTED_INIT_STORE_STORAGE_KIND="None"
declare -x TORCH_DISTRIBUTED_INIT_STORE_STORAGE_NAME="MustSpecifyViaApplicationParameters"
declare -x TZ="US/Pacific"
declare -x UNMOUNT_RETRY_COUNT="5"
declare -x USER_ALIAS="8a589725-7622-41da-8182-8da81127dd72"
declare -x USER_DEFINED_ENV_VAR_0="QVpVUkVNTF9SVU5fSUQ9aGVscGZ1bF9zaGFtcG9vX21qMGN2bDRrY2c7TlVMO0FaVVJFTUxfUlVOX0NPTkZJR1VSQVRJT049YXp1cmVtbC1zZXR1cC9tdXRhdGVkX3J1bl9jb25maWd1cmF0aW9uLmpzb247TlVMO0FaVVJFTUxfU0VSVklDRV9FTkRQT0lOVD1odHRwczovL3dlc3R1czIuYXBpLmF6dXJlbWwubXM7TlVMO0FaVVJFTUxfU0VSVklDRV9DRVJUX0VORFBPSU5UPWh0dHBzOi8vd2VzdHVzMi5jZXJ0LmFwaS5henVyZW1sLm1zO05VTDtBWlVSRU1MX1JVTl9ISVNUT1JZX1NFUlZJQ0VfRU5EUE9JTlQ9aHR0cHM6Ly93ZXN0dXMyLmFwaS5henVyZW1sLm1zO05VTDtBWlVSRU1MX1dPUktTUEFDRV9TQ09QRT0vc3Vic2NyaXB0aW9ucy9jNGM1MzRiYy05OTc4LTQ5NzQtOWM4Ny01NTFmN2M1NzU0ZWYvcmVzb3VyY2VHcm91cHMvbXNyYS1zaC1hbWwtcmcvcHJvdmlkZXJzL01pY3Jvc29mdC5NYWNoaW5lTGVhcm5pbmdTZXJ2aWNlcy93b3Jrc3BhY2VzL21zcmEtc2gtYW1sLXdzO05VTDtBWlVSRU1MX0VYUEVSSU1FTlRfU0NPUEU9L3N1YnNjcmlwdGlvbnMvYzRjNTM0YmMtOTk3OC00OTc0LTljODctNTUxZjdjNTc1NGVmL3Jlc291cmNlR3JvdXBzL21zcmEtc2gtYW1sLXJnL3Byb3ZpZGVycy9NaWNyb3NvZnQuTWFjaGluZUxlYXJuaW5nU2VydmljZXMvd29ya3NwYWNlcy9tc3JhLXNoLWFtbC13cy9leHBlcmltZW50cy92bGxtLXNoLWdjcjEyMzAxLWFiZDkxNThmO05VTDtBWlVSRU1MX0FSTV9SRVNPVVJDRUdST1VQPW1zcmEtc2gtYW1sLXJnO05VTDtBWlVSRU1MX0FSTV9TVUJTQ1JJUFRJT049YzRjNTM0YmMtOTk3OC00OTc0LTljODctNTUxZjdjNTc1NGVmO05VTDtBWlVSRU1MX0FSTV9XT1JLU1BBQ0VfTkFNRT1tc3JhLXNoLWFtbC13cztOVUw7QVpVUkVNTF9BUk1fUFJPSkVDVF9OQU1FPXZsbG0tc2gtZ2NyMTIzMDEtYWJkOTE1OGY7TlVMO0FaVVJFTUxfRVhQRVJJTUVOVF9JRD04ZGRiYTQ3Yi01NDQyLTQwMDAtOGJkMi1iZTU1ODg1N2VjY2U7TlVMO0FaVVJFTUxfUlVOX1RPS0VOX1BBU1M9NTBlMTMyN2EtMjU4OC00YzA1LWJlZjctNTliYjEyZjExMzI2O05VTDtBWlVSRU1MX1JVTl9UT0tFTl9SQU5EPWIyZDg1ZTBhLWUyNDUtNGYwYS1iNzM0LTc4YmI0N2U4YTc4MztOVUw7QVpVUkVNTF9SVU5fVE9LRU49ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNklqaERNVEF6UVRSRE1FSTNRVEF4UXpReU9URTNR"
declare -x USER_DEFINED_ENV_VAR_1="VGxCTXpWQ1JqSkVNa0UyTkVReU1USTJOREFpTENKMGVYQWlPaUpLVjFRaWZRLmV5SnliMnhsSWpvaVEyOXVkSEpwWW5WMGIzSWlMQ0p6WTI5d1pTSTZJaTl6ZFdKelkzSnBjSFJwYjI1ekwyTTBZelV6TkdKakxUazVOemd0TkRrM05DMDVZemczTFRVMU1XWTNZelUzTlRSbFppOXlaWE52ZFhKalpVZHliM1Z3Y3k5dGMzSmhMWE5vTFdGdGJDMXlaeTl3Y205MmFXUmxjbk12VFdsamNtOXpiMlowTGsxaFkyaHBibVZNWldGeWJtbHVaMU5sY25acFkyVnpMM2R2Y210emNHRmpaWE12YlhOeVlTMXphQzFoYld3dGQzTWlMQ0poWTJOdmRXNTBhV1FpT2lJd01EQXdNREF3TUMwd01EQXdMVEF3TURBdE1EQXdNQzB3TURBd01EQXdNREF3TURBaUxDSjNiM0pyYzNCaFkyVkpaQ0k2SW1Sak1XSmpOVFl3TFdNMk16QXROR0psTmkxaVpHWXpMVFkzWlRFek5qYzBNemRrT1NJc0luQnliMnBsWTNScFpDSTZJakF3TURBd01EQXdMVEF3TURBdE1EQXdNQzB3TURBd0xUQXdNREF3TURBd01EQXdNQ0lzSW1ScGMyTnZkbVZ5ZVNJNkluVnlhVG92TDJScGMyTnZkbVZ5ZVhWeWFTOGlMQ0owYVdRaU9pSTNNbVk1T0RoaVppMDRObVl4TFRReFlXWXRPVEZoWWkweVpEZGpaREF4TVdSaU5EY2lMQ0p2YVdRaU9pSTRZVFU0T1RjeU5TMDNOakl5TFRReFpHRXRPREU0TWkwNFpHRTRNVEV5TjJSa056SWlMQ0p3ZFdsa0lqb2lNVEF3TXpJd01ETTRSRE0wTUVVek15SXNJbWx6Y3lJNkltRjZkWEpsYld3aUxDSmhjSEJwWkNJNklsbHBabUZ1SUZsaGJtY2dLRk5ETFVGTVZDa2lMQ0psZUhBaU9qRTNOelV5TkRVMk56TXNJbUYxWkNJNkltRjZkWEpsYld3aWZRLnFVTld6Q3NPUVJJbUphUEhUeTBFY2EweEticExRZ0JzRU1wY3d3N0E3Vkt4Xzh1ODQ4am82c1diU2xXT0JDUnN2d3BlNTZMa1NWdEhpcXJLc1ZfdGxsWU5pNXZjOVdKQWRwQTZtNnQ5QXJwLUV5bThaTHZnZVpLc3BvQUxIc1lIS2FkMzFxdU5nQ19BR0xlYnJNbmlzUW9XYTk4YUxwdll5akhtMlA4ZXZ1SDlXMkd6X191TGFtbVg0QzBPSHVVSThzTjE5NDFOR3RGeVVodzlPbkllbU4zdV9GaXBMS2JrOHlNQXdtTlBzRG5sRXBCdE11UEVZMF9HbG1DcmxyeWFnV1pzVWtLNnM1bnRUZnM4YVo0WktmS1B5Uno0WEhGWWtXS2JLQm9wTk1mVWRmOUZzWURsYU42Nm1EbkJKdjYzQ2xZb3Q1UWpvR1lzWC1xSDA5c3VQdztOVUw7QVpVUkVNTF9SVU5fVE9LRU5fRVhQSVJZPTE3NzUyNDU2NzM7TlVMO0FaVVJFTUxf"
declare -x USER_DEFINED_ENV_VAR_10=""
declare -x USER_DEFINED_ENV_VAR_11=""
declare -x USER_DEFINED_ENV_VAR_12=""
declare -x USER_DEFINED_ENV_VAR_13=""
declare -x USER_DEFINED_ENV_VAR_14=""
declare -x USER_DEFINED_ENV_VAR_15=""
declare -x USER_DEFINED_ENV_VAR_16=""
declare -x USER_DEFINED_ENV_VAR_17=""
declare -x USER_DEFINED_ENV_VAR_18=""
declare -x USER_DEFINED_ENV_VAR_19=""
declare -x USER_DEFINED_ENV_VAR_2="REFUQVJFRkVSRU5DRV9kYXRhPS9kYXRhc2V0cztOVUw7QVpVUkVNTF9EQVRBUkVGRVJFTkNFX3plaHVpPS96ZWh1aTtOVUw7QVpVUkVNTF9EQVRBUkVGRVJFTkNFX291dHB1dD0vb3V0cHV0O05VTDtBWlVSRU1MX0RBVEFSRUZFUkVOQ0VfaW5wdXQ9L2Jsb2I7TlVMO0FaVVJFTUxfREFUQVJFRkVSRU5DRV9hbWx0X2RlZmF1bHQ9L21udC9kZWZhdWx0O05VTDtKT0JfRVhFQ1VUSU9OX01PREU9YmFzaWM7TlVMO0RQUkVQX1JTTEVYX0xPR19TVERPVVQ9dHJ1ZTtOVUw7RFBSRVBfUlNMRVhfTE9HX1NURE9VVF9TQ1JVQkJFRD10cnVlO05VTDtTSU5HVUxBUklUWV9ESVNBQkxFX0ZBVEFMX09OR09JTkdfU1NIX0NIRUNLX0ZBSUw9dHJ1ZTtOVUw7QVpVUkVNTF9QWVRIT05fSU5URVJQUkVURVJfUEFUSD1weXRob247TlVMO0FaVVJFTUxfVVNFUl9PSUQ9OGE1ODk3MjUtNzYyMi00MWRhLTgxODItOGRhODExMjdkZDcyO05VTDtBWlVSRU1MX0NPTVBVVEVfTkFNRT1haXN1cGVyY29tcHV0ZXI7TlVMO0FaX1NJTkdVTEFSSVRZX1NURE9VVEVSUl9QQVRIPS9zY3JhdGNoL3dvcmtzcGFjZWJsb2JzdG9yZS9henVyZW1sL2hlbHBmdWxfc2hhbXBvb19tajBjdmw0a2NnL2F6dXJlbWxfY29tcHV0ZV9sb2dzO05VTDtTQVNfVVJMX0ZPUl9CTE9CX0xFQVNFPSdodHRwczovL21zcmFzaGFtbHdzNDQ2NjQ2MDA5Mi5ibG9iLmNvcmUud2luZG93cy5uZXQvYXp1cmVtbC1ibG9ic3RvcmUtZGMxYmM1NjAtYzYzMC00YmU2LWJkZjMtNjdlMTM2NzQzN2Q5L2F6dXJlbWwvaGVscGZ1bF9zaGFtcG9vX21qMGN2bDRrY2cvTGVhc2VCbG9iXz9zdj0yMDE5LTA3LTA3JnNyPWMmc2lnPU5FbndwSmNUUFlIbjdkQyUyQlR5ZW4xWFc4aW5CVkprRjA1SXkwJTJGZk5xNWQwJTNEJnNrb2lkPTc4MGNiMGM0LTE4YTEtNGJlMy05MjJiLWE2NmY0ODRkMTU1NyZza3RpZD03MmY5ODhiZi04NmYxLTQxYWYtOTFhYi0yZDdjZDAxMWRiNDcmc2t0PTIwMjYtMDMtMTNUMTclM0EwNSUzQTQ5WiZza2U9MjAyNi0wMy0yMFQxNyUzQTA1JTNBNDlaJnNrcz1iJnNrdj0yMDE5LTA3LTA3JnN0PTIwMjYtMDMtMTNUMTclM0EzNyUzQTU3WiZzZT0yMDI2LTAzLTIwVDE2JTNBNTUlM0E0OVomc3A9cmN3bCc7TlVMO0FaVVJFX0NMSUVOVF9JRD00ODYyYTA2ZC1jNmM1LTRiZTUtODBjOS05ODc1ZWMzZDkzYjM7TlVMO0NVU1RPTV9QUk9NX1RPS0VOX1BST0dSQU09J2V4cG9ydCBB"
declare -x USER_DEFINED_ENV_VAR_20=""
declare -x USER_DEFINED_ENV_VAR_21=""
declare -x USER_DEFINED_ENV_VAR_22=""
declare -x USER_DEFINED_ENV_VAR_23=""
declare -x USER_DEFINED_ENV_VAR_24=""
declare -x USER_DEFINED_ENV_VAR_25=""
declare -x USER_DEFINED_ENV_VAR_26=""
declare -x USER_DEFINED_ENV_VAR_27=""
declare -x USER_DEFINED_ENV_VAR_28=""
declare -x USER_DEFINED_ENV_VAR_29=""
declare -x USER_DEFINED_ENV_VAR_3="WlVSRU1MX1JVTl9UT0tFTl9GSUxFPS9zY3JhdGNoL3dvcmtzcGFjZWJsb2JzdG9yZS9henVyZW1sL2hlbHBmdWxfc2hhbXBvb19tajBjdmw0a2NnLy5lbmNyeXB0ZWRfcnVudG9rZW47aWYgWyAtZiAiJEFaVVJFTUxfUlVOX1RPS0VOX0ZJTEUiIF07IHRoZW4gQUVTX0tFWT0kKGVjaG8gJHtBWlVSRU1MX1JVTl9VTklRVUVfU1lNTUVUUklDX0tFWX0gfCBvcGVuc3NsIGJhc2U2NCAtZCB8IHh4ZCAtcCAtYzMyKTtBRVNfSVY9JChlY2hvICR7QVpVUkVNTF9SVU5fSVZ9IHwgb3BlbnNzbCBiYXNlNjQgLWQgfCB4eGQgLXAgLWMzMik7UlVOX1RPS0VOPSQoY2F0ICR7QVpVUkVNTF9SVU5fVE9LRU5fRklMRX0gfCBvcGVuc3NsIGVuYyAtYWVzLTI1Ni1jYmMgLWQgLWEgLUsgJHtBRVNfS0VZfSAtaXYgJHtBRVNfSVZ9IC1BKTsgZWNobyAkUlVOX1RPS0VOO2Vsc2UgZXhwb3J0IEFaVVJFTUxfUlVOX1RPS0VOPSQoY3VybCAtcyAiJHtBWlVSRU1MX1JVTl9ISVNUT1JZX1NFUlZJQ0VfRU5EUE9JTlR9L2hpc3RvcnkvdjEuMCR7QVpVUkVNTF9XT1JLU1BBQ0VfU0NPUEV9L2V4cGVyaW1lbnRpZHMvJHtBWlVSRU1MX0VYUEVSSU1FTlRfSUR9L3J1bnMvJHtBWlVSRU1MX1JVTl9JRH0vdG9rZW4iIC1IICJBY2NlcHQ6IGFwcGxpY2F0aW9uIC8ganNvbiIgLUggIkF1dGhvcml6YXRpb246IEJlYXJlciAke0FaVVJFTUxfUlVOX1RPS0VOfSIgfCBqcSAtciAiLnRva2VuIikgJiYgZWNobyAkQVpVUkVNTF9SVU5fVE9LRU47IGZpJztOVUw7Q1VTVE9NX1BST01fVE9LRU5fUFJPR1JBTV9BUkdTPTs7TlVMO0NVU1RPTV9QUk9NX1RPS0VOX1JFRlJFU0hfSU5URVJWQUxfSU5fU0VDT05EUz0yNzAwO05VTDtDVVNUT01fUFJPTV9FTkRQT0lOVD0ke0FaVVJFTUxfUlVOX0hJU1RPUllfU0VSVklDRV9FTkRQT0lOVH0vbWV0cmljL3YyLjAke0FaVVJFTUxfV09SS1NQQUNFX1NDT1BFfS9hcGkvMi4wL3Byb21ldGhldXMvcG9zdDtOVUw7Q1VTVE9NX1BST01fV1JJVEVfUkVMQUJFTF9DT05GSUc9JyAgICAtIHNvdXJjZV9sYWJlbHM6IFttaW5vcl9udW1iZXIsdW5pcXVlX2xhYmVsX25hbWVdX3l0aXJhbHVnbmlzXyAgICAgIGFjdGlvbjogcmVwbGFjZV95dGlyYWx1Z25pc18gICAgICB0YXJnZXRfbGFiZWw6IERldmljZUlkX3l0aXJhbHVnbmlzXyAgICAgIHJlZ2V4OiAoLispO3VuaXF1ZV9sYWJlbF92YWx1ZV95dGlyYWx1Z25pc18gICAgLSBzb3Vy"
declare -x USER_DEFINED_ENV_VAR_4="Y2VfbGFiZWxzOiBbZ3B1X2lkLHVuaXF1ZV9sYWJlbF9uYW1lXV95dGlyYWx1Z25pc18gICAgICBhY3Rpb246IHJlcGxhY2VfeXRpcmFsdWduaXNfICAgICAgdGFyZ2V0X2xhYmVsOiBEZXZpY2VJZF95dGlyYWx1Z25pc18gICAgICByZWdleDogKC4rKTt1bmlxdWVfbGFiZWxfdmFsdWVfeXRpcmFsdWduaXNfICAgIC0gc291cmNlX2xhYmVsczogW3VuaXF1ZV9sYWJlbF9uYW1lXV95dGlyYWx1Z25pc18gICAgICBhY3Rpb246IHJlcGxhY2VfeXRpcmFsdWduaXNfICAgICAgdGFyZ2V0X2xhYmVsOiBhenVyZW1sX21ldHJpY19zdG9yYWdlX3l0aXJhbHVnbmlzXyAgICAgIHJlZ2V4OiB1bmlxdWVfbGFiZWxfdmFsdWVfeXRpcmFsdWduaXNfICAgICAgcmVwbGFjZW1lbnQ6IDFfeXRpcmFsdWduaXNfICAgIC0gc291cmNlX2xhYmVsczogW3VuaXF1ZV9sYWJlbF9uYW1lXV95dGlyYWx1Z25pc18gICAgICBhY3Rpb246IHJlcGxhY2VfeXRpcmFsdWduaXNfICAgICAgdGFyZ2V0X2xhYmVsOiBhenVyZW1sX21ldHJpY19uYW1lc3BhY2VfeXRpcmFsdWduaXNfICAgICAgcmVnZXg6IHVuaXF1ZV9sYWJlbF92YWx1ZV95dGlyYWx1Z25pc18gICAgICByZXBsYWNlbWVudDogdmllbm5hX3l0aXJhbHVnbmlzXyAgICAtIHNvdXJjZV9sYWJlbHM6IFt1bmlxdWVfbGFiZWxfbmFtZV1feXRpcmFsdWduaXNfICAgICAgYWN0aW9uOiByZXBsYWNlX3l0aXJhbHVnbmlzXyAgICAgIHRhcmdldF9sYWJlbDogYXp1cmVtbF9yZXNvdXJjZWlkX3l0aXJhbHVnbmlzXyAgICAgIHJlZ2V4OiB1bmlxdWVfbGFiZWxfdmFsdWVfeXRpcmFsdWduaXNfICAgICAgcmVwbGFjZW1lbnQ6IC9zdWJzY3JpcHRpb25zL2M0YzUzNGJjLTk5NzgtNDk3NC05Yzg3LTU1MWY3YzU3NTRlZi9yZXNvdXJjZUdyb3Vwcy9tc3JhLXNoLWFtbC1yZy9wcm92aWRlcnMvTWljcm9zb2Z0Lk1hY2hpbmVMZWFybmluZ1NlcnZpY2VzL3dvcmtzcGFjZXMvbXNyYS1zaC1hbWwtd3NfeXRpcmFsdWduaXNfICAgIC0gc291cmNlX2xhYmVsczogW3VuaXF1ZV9sYWJlbF9uYW1lXV95dGlyYWx1Z25pc18gICAgICBhY3Rpb246IHJlcGxhY2VfeXRpcmFsdWduaXNfICAgICAgdGFyZ2V0X2xhYmVsOiBydW5JZF95dGlyYWx1Z25pc18gICAgICByZWdleDogdW5pcXVlX2xhYmVsX3ZhbHVlX3l0aXJhbHVnbmlzXyAgICAgIHJlcGxhY2VtZW50OiBoZWxwZnVsX3NoYW1wb29fbWowY3ZsNGtjZ195"
declare -x USER_DEFINED_ENV_VAR_5="dGlyYWx1Z25pc18gICAgLSBzb3VyY2VfbGFiZWxzOiBbdW5pcXVlX2xhYmVsX25hbWVdX3l0aXJhbHVnbmlzXyAgICAgIGFjdGlvbjogcmVwbGFjZV95dGlyYWx1Z25pc18gICAgICB0YXJnZXRfbGFiZWw6IENvbXB1dGVOYW1lX3l0aXJhbHVnbmlzXyAgICAgIHJlZ2V4OiB1bmlxdWVfbGFiZWxfdmFsdWVfeXRpcmFsdWduaXNfICAgICAgcmVwbGFjZW1lbnQ6IG1zcnJlc3JjaHZjX3l0aXJhbHVnbmlzXyAgICAtIHNvdXJjZV9sYWJlbHM6IFt1bmlxdWVfbGFiZWxfbmFtZV1feXRpcmFsdWduaXNfICAgICAgYWN0aW9uOiBrZWVwX3l0aXJhbHVnbmlzXyAgICAgIHJlZ2V4OiB1bmlxdWVfbGFiZWxfdmFsdWVfeXRpcmFsdWduaXNfICAgIC0gc291cmNlX2xhYmVsczogW2luc3RhbmNlLHVuaXF1ZV9sYWJlbF9uYW1lXV95dGlyYWx1Z25pc18gICAgICBhY3Rpb246IHJlcGxhY2VfeXRpcmFsdWduaXNfICAgICAgdGFyZ2V0X2xhYmVsOiBJbnN0YW5jZUlkX3l0aXJhbHVnbmlzXyAgICAgIHJlZ2V4OiAoLispO3VuaXF1ZV9sYWJlbF92YWx1ZV95dGlyYWx1Z25pc18gICAgLSBzb3VyY2VfbGFiZWxzOiBbX19uYW1lX19dX3l0aXJhbHVnbmlzXyAgICAgIGFjdGlvbjogcmVwbGFjZV95dGlyYWx1Z25pc18gICAgICB0YXJnZXRfbGFiZWw6IHJvb3RSdW5JZF95dGlyYWx1Z25pc18gICAgICByZWdleDogR3B1RW5lcmd5Sm91bGVzX3l0aXJhbHVnbmlzXyAgICAgIHJlcGxhY2VtZW50OiBoZWxwZnVsX3NoYW1wb29fbWowY3ZsNGtjZ195dGlyYWx1Z25pc18gICAgLSBzb3VyY2VfbGFiZWxzOiBbZGV2aWNlLHVuaXF1ZV9sYWJlbF9uYW1lXV95dGlyYWx1Z25pc18gICAgICBhY3Rpb246IHJlcGxhY2VfeXRpcmFsdWduaXNfICAgICAgdGFyZ2V0X2xhYmVsOiBEZXZpY2VJZF95dGlyYWx1Z25pc18gICAgICByZWdleDogKC4rKTt1bmlxdWVfbGFiZWxfdmFsdWUnO05VTDtBWlVSRU1MX1JVTlRJTUVfSk9CX1NQRUNfSEFTSD1iYzUzYzcwMmNmMzg5NWQwODczMjc0NjRhNGUwOWZlNTlmZWNiMmUyZWI3OGQ1N2RmMTU2YWNiNzZmODk2YzRjO05VTDtBWlVSRU1MX1JVTl9VTklRVUVfU1lNTUVUUklDX0tFWT1YdkpTWHQ3K0IxS21GeFNkcG5ST0VwREtHOWZYaldlcjhnUlBZakRFNVhNPTtOVUw7QVpVUkVNTF9SVU5fSVY9aEIxSHZyemNSTDZZNm1NQWlhbGlFZz09O05VTDtTSU5HVUxBUklUWV9FTkFCTEVfUFJPQ0VTU19SRVNPVVJD"
declare -x USER_DEFINED_ENV_VAR_6="RV9FWFBPUlRFUj1mYWxzZTtOVUw7RU5BQkxFX1NJREVDQVI9dHJ1ZTtOVUw7QVpVUkVNTF9SVU5USU1FX0pPQl9TUEVDX0ZJTEVfUEFUSD0vc2NyYXRjaC93b3Jrc3BhY2VibG9ic3RvcmUvYXp1cmVtbC9oZWxwZnVsX3NoYW1wb29fbWowY3ZsNGtjZy8uam9ic3BlYztOVUw7U0lOR1VMQVJJVFlfU0lERUNBUl9DT05TT0xJREFUSU9OPXRydWU7TlVMO1VTRVJfU0lERUNBUl9QUk9HUkFNPWJhc2g7TlVMO1VTRVJfU0lERUNBUl9QUk9HUkFNX0FSR1M9JyRTSURFQ0FSX1NUQVJUX1NDUklQVCAvb3B0L21pY3Jvc29mdC9henVyZW1sIDEnO05VTDtVU0VSX1NJREVDQVJfSU1BR0VfTkFNRT1tY3IubWljcm9zb2Z0LmNvbS9henVyZW1sL3J1bnRpbWUvYm9vdC9zaW5ndWxhcml0eS1ib290c3RyYXBwZXIvaW5zdGFsbGVkOjAuMC4xLjIwMjYwMjI3LjE7TlVMO1VTRVJfU0lERUNBUl9BQ1JfTkFNRT1henVyZV91c2VybmFtZTtOVUw7VVNFUl9TSURFQ0FSX0FDUl9QQVNTV09SRD1henVyZV9wYXNzd29yZDtOVUw7U0lERUNBUl9TVEFSVF9TQ1JJUFQ9L29wdC9taWNyb3NvZnQvYXp1cmVtbC9zaWRlY2FycnVuLmJhc2g7TlVMO0FaVVJFTUxfUlVOVElNRV9KT0JfU1BFQ19TQVNfVVJMPSdodHRwczovL21zcmFzaGFtbHdzNDQ2NjQ2MDA5Mi5ibG9iLmNvcmUud2luZG93cy5uZXQvYXp1cmVtbC1ibG9ic3RvcmUtZGMxYmM1NjAtYzYzMC00YmU2LWJkZjMtNjdlMTM2NzQzN2Q5L2F6dXJlbWwvaGVscGZ1bF9zaGFtcG9vX21qMGN2bDRrY2cvLmpvYnNwZWM/c3Y9MjAxOS0wNy0wNyZzcj1jJnNpZz1odFk5SWtvREtvUGJrbHdjS2VWRjNpSzlhU2lwUGh4eXozYXQlMkJPekVXOXMlM0Qmc2tvaWQ9NzgwY2IwYzQtMThhMS00YmUzLTkyMmItYTY2ZjQ4NGQxNTU3JnNrdGlkPTcyZjk4OGJmLTg2ZjEtNDFhZi05MWFiLTJkN2NkMDExZGI0NyZza3Q9MjAyNi0wMy0xM1QxNyUzQTA1JTNBNDlaJnNrZT0yMDI2LTAzLTIwVDE3JTNBMDUlM0E0OVomc2tzPWImc2t2PTIwMTktMDctMDcmc3Q9MjAyNi0wMy0xM1QxNyUzQTM3JTNBNTdaJnNlPTIwMjYtMDMtMjBUMTYlM0E1NSUzQTQ5WiZzcD1yJztOVUw7VVNFUl9BTElBUz04YTU4OTcyNS03NjIyLTQxZGEtODE4Mi04ZGE4MTEyN2RkNzI7TlVMOw=="
declare -x USER_DEFINED_ENV_VAR_7=""
declare -x USER_DEFINED_ENV_VAR_8=""
declare -x USER_DEFINED_ENV_VAR_9=""
declare -x USER_NODE_AGENT_PORT="9200"
declare -x USER_NODE_AGENT_PROMETHEUS_PORT="10007"
declare -x USER_NODE_AGENT_ROOT_PATH="node_agent"
declare -x USER_NODE_AGENT_SUPPORTS_DIRECT_CONNECTIVITY="true"
declare -x USER_SERVICE_PROGRAM=""
declare -x USER_SERVICE_PROGRAM_1=""
declare -x USER_SERVICE_PROGRAM_2=""
declare -x USER_SERVICE_PROGRAM_3=""
declare -x USER_SERVICE_PROGRAM_4=""
declare -x USER_SERVICE_PROGRAM_5=""
declare -x USER_SERVICE_PROGRAM_6=""
declare -x USER_SERVICE_PROGRAM_ARGS=""
declare -x USER_SERVICE_PROGRAM_ARGS_1=""
declare -x USER_SERVICE_PROGRAM_ARGS_2=""
declare -x USER_SERVICE_PROGRAM_ARGS_3=""
declare -x USER_SERVICE_PROGRAM_ARGS_4=""
declare -x USER_SERVICE_PROGRAM_ARGS_5=""
declare -x USER_SERVICE_PROGRAM_ARGS_6=""
declare -x USER_SIDECAR_ACR_NAME="azure_username"
declare -x USER_SIDECAR_ACR_PASSWORD="azure_password"
declare -x USER_SIDECAR_IMAGE_NAME="mcr.microsoft.com/azureml/runtime/boot/singularity-bootstrapper/installed:0.0.1.20260227.1"
declare -x USER_SIDECAR_PROGRAM="bash"
declare -x USER_SIDECAR_PROGRAM_ARGS="\$SIDECAR_START_SCRIPT /opt/microsoft/azureml 1"
declare -x WANDB_NAME="yif-unirun-4x80Ga100"
declare -x WANDB_NOTES="yasheng-unirun"
declare -x WANDB_PROJECT="vllm-sh-gcr12301"
declare -x WANDB_RUN_GROUP="polite-anchovy"
declare -x WANDB_RUN_ID="7226550736.03454-e95bcd5a-1159"
declare -x WORLD_SIZE="1"
declare -x ZEHUI="/zehui/"
declare -x _AZUREML_SINGULARITY_JOB_UAI="/subscriptions/c4c534bc-9978-4974-9c87-551f7c5754ef/resourceGroups/msra-sh-aml-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/msra-sh-aml-uai"
declare -x __UNA_V2_MODE__="true"
declare -x amlt_code="/tmp/amlt-code-download"
declare -x amlt_default="/mnt/default/"
declare -x amlt_results="/scratch/azureml/cr/j/b5e4aee59bb6481db8ad5d94681dd957/cap/data-capability/wd/amlt_results"
declare -x azure_ml_input_amlt_code="/tmp/amlt-code-download"
declare -x azure_ml_output_amlt_default="/mnt/default/"
declare -x azure_ml_output_amlt_results="/scratch/azureml/cr/j/b5e4aee59bb6481db8ad5d94681dd957/cap/data-capability/wd/amlt_results"
declare -x azure_ml_output_data="/datasets/"
declare -x azure_ml_output_input="/blob/"
declare -x azure_ml_output_output="/output/"
declare -x azure_ml_output_zehui="/zehui/"
declare -x azureml_datareference_amlt_code="/tmp/amlt-code-download"
declare -x azureml_datareference_azure_ml_input_amlt_code="/tmp/amlt-code-download"
declare -x data="/datasets/"
declare -x input="/blob/"
declare -x output="/output/"
declare -x zehui="/zehui/"
